export interface EducationalFact {
  emoji: string;
 factTr: string;
 factEn: string;
 funFactTr: string;
 funFactEn: string;
}

export const EDUCATIONAL_FACTS: Record<string, EducationalFact> = {
  // ===== HAYVANLAR =====
  'hayvanlar-01': {
    emoji: '🐱',
 factTr:'Kediler çok temiz hayvanlardır ve günün üçte birini kendilerini temizleyerek geçirirler!',
 factEn:'Cats are very clean animals and spend one-third of their day grooming themselves!',
 funFactTr:'Kediler 100\'den fazla farklı ses çıkarabilir!',
 funFactEn:'Cats can make over 100 different sounds!',
  },
  'hayvanlar-02': {
    emoji: '🐶',
 factTr:'Köpekler insanların en iyi arkadaşıdır ve 15.000 yıldır bizimle yaşıyorlar!',
 factEn:'Dogs are humans\' best friends and have lived with us for 15,000 years!',
 funFactTr:'Köpekler kokuyu insanlardan 10.000 kat daha iyi alabilir!',
 funFactEn:'Dogs can smell 10,000 times better than humans!',
  },
  'hayvanlar-03': {
    emoji: '🦁',
 factTr:'Aslanlar aslında ormanda değil, Afrika çayırlarında ve savanalarında yaşar!',
 factEn:'Lions actually live in African grasslands and savannas, not in jungles!',
 funFactTr:'Bir aslanın kükremesi 8 km uzaktan duyulabilir!',
 funFactEn:'A lion\'s roar can be heard from 8 km away!',
  },
  'hayvanlar-04': {
    emoji: '🐘',
 factTr:'Filler karada yaşayan en büyük hayvanlardır ve çok iyi hafızaları vardır!',
 factEn:'Elephants are the largest land animals and have excellent memories!',
 funFactTr:'Filler hortumlarıyla su püskürtüp duş alabilirler!',
 funFactEn:'Elephants can spray water with their trunks to take a shower!',
  },
  'hayvanlar-05': {
    emoji: '🦋',
 factTr:'Kelebekler tırtılken başlar ve sonra güzel kanatlara sahip olurlar!',
 factEn:'Butterflies start as caterpillars and then grow beautiful wings!',
 funFactTr:'Kelebekler tatları ayaklarıyla alır!',
 funFactEn:'Butterflies taste with their feet!',
  },
  'hayvanlar-06': {
    emoji: '🐰',
 factTr:'Tavşanlar çok hızlı koşabilir ve büyük kulakları sesleri çok iyi duyar!',
 factEn:'Rabbits can run very fast and their big ears hear sounds very well!',
 funFactTr:'Tavşanlar mutlu olduklarında havaya zıplayıp dönerler!',
 funFactEn:'Rabbits jump and twist in the air when they\'re happy!',
  },
  'hayvanlar-07': {
    emoji: '🐠',
 factTr:'Denizlerde 30.000\'den fazla farklı balık türü yaşar!',
 factEn:'There are over 30,000 different species of fish in the oceans!',
 funFactTr:'Bazı balıklar karanlıkta parlayabilir!',
 funFactEn:'Some fish can glow in the dark!',
  },
  'hayvanlar-08': {
    emoji: '🐦',
 factTr:'Kuşlar dinozorların torunlarıdır ve dünyada 10.000\'den fazla kuş türü vardır!',
 factEn:'Birds are descendants of dinosaurs, and there are over 10,000 bird species!',
 funFactTr:'Papağanlar insan konuşmasını taklit edebilir!',
 funFactEn:'Parrots can mimic human speech!',
  },
  'hayvanlar-09': {
    emoji: '🐴',
 factTr:'Atlar ayakta uyuyabilir ve çok güçlü hayvanlardır!',
 factEn:'Horses can sleep standing up and are very strong animals!',
 funFactTr:'Atlar neredeyse 360 derece görebilir!',
 funFactEn:'Horses can see almost 360 degrees around them!',
  },
  'hayvanlar-10': {
    emoji: '🐻',
 factTr:'Ayılar kışın uyurlar ve bu uyku bazen 5-7 ay sürebilir!',
 factEn:'Bears hibernate in winter, and this sleep can last 5-7 months!',
 funFactTr:'Ayılar köpeklerden daha iyi koklayabilir!',
 funFactEn:'Bears have a better sense of smell than dogs!',
  },
  // ===== UZAY =====
  'uzay-01': {
    emoji: '🚀',
 factTr:'Roketler uzaya çıkmak için saniyede 11 km hızla gitmek zorundadır!',
 factEn:'Rockets need to travel at 11 km per second to reach space!',
 funFactTr:'Uzaydaki ilk hayvan Laika isimli bir köpekti!',
 funFactEn:'The first animal in space was a dog named Laika!',
  },
  'uzay-02': {
    emoji: '👨‍🚀',
 factTr:'Astronotlar uzayda yüzerler çünkü orada yerçekimi çok azdır!',
 factEn:'Astronauts float in space because there is very little gravity!',
 funFactTr:'Uzayda ağlayamazsın çünkü gözyaşları yüzer!',
 funFactEn:'You can\'t cry in space because tears just float!',
  },
  'uzay-03': {
    emoji: '🪐',
 factTr:'Güneş sistemimizde 8 gezegen vardır ve Dünya üçüncüsüdür!',
 factEn:'Our solar system has 8 planets, and Earth is the third one!',
 funFactTr:'Jüpiter o kadar büyük ki içine 1.300 Dünya sığar!',
 funFactEn:'Jupiter is so big that 1,300 Earths could fit inside it!',
  },
  'uzay-04': {
    emoji: '⭐',
 factTr:'Gökyüzündeki yıldızlar aslında çok uzaktaki devasa güneşlerdir!',
 factEn:'Stars in the sky are actually giant suns that are very far away!',
 funFactTr:'Gece gökyüzünde gözle 5.000 yıldız görebilirsin!',
 funFactEn:'You can see about 5,000 stars with your eyes at night!',
  },
  'uzay-05': {
    emoji: '👽',
 factTr:'Bilim insanları uzayda başka canlılar olup olmadığını araştırıyor!',
 factEn:'Scientists are researching whether there is life elsewhere in space!',
 funFactTr:'Evrendeki yıldız sayısı dünyadaki kum tanelerinden fazla!',
 funFactEn:'There are more stars in the universe than grains of sand on Earth!',
  },
  'uzay-06': {
    emoji: '🛸',
 factTr:'Uzay gemileri güneş panelleriyle enerji üretir!',
 factEn:'Spaceships generate energy using solar panels!',
 funFactTr:'Uluslararası Uzay İstasyonu saatte 28.000 km hızla gider!',
 funFactEn:'The International Space Station travels at 28,000 km per hour!',
  },
  'uzay-07': {
    emoji: '🌙',
 factTr:'Ay, Dünya\'nın tek doğal uydusudur ve gecelerimizi aydınlatır!',
 factEn:'The Moon is Earth\'s only natural satellite and lights up our nights!',
 funFactTr:'Ay\'da yürüyen iz sonsuza kadar kalır çünkü rüzgar yok!',
 funFactEn:'Footprints on the Moon last forever because there\'s no wind!',
  },
  'uzay-08': {
    emoji: '☀️',
 factTr:'Güneş bir yıldızdır ve Dünya\'ya ışık ve sıcaklık verir!',
 factEn:'The Sun is a star that gives Earth light and warmth!',
 funFactTr:'Güneş\'in içine 1 milyon Dünya sığar!',
 funFactEn:'One million Earths could fit inside the Sun!',
  },
  'uzay-09': {
    emoji: '🪐',
 factTr:'Satürn\'ün etrafındaki halkalar buz ve kaya parçalarından oluşur!',
 factEn:'Saturn\'s rings are made of pieces of ice and rock!',
 funFactTr:'Satürn o kadar hafif ki suyun üstünde yüzebilir!',
 funFactEn:'Saturn is so light it could float on water!',
  },
  'uzay-10': {
    emoji: '🛸',
 factTr:'UFO "tanımlanamayan uçan cisim" demektir!',
 factEn:'UFO stands for "Unidentified Flying Object"!',
 funFactTr:'Her yıl binlerce kişi gökyüzünde ilginç şeyler gördüğünü söyler!',
 funFactEn:'Thousands of people report seeing strange things in the sky every year!',
  },
  // ===== DENİZ =====
  'deniz-01': {
    emoji: '🐋',
 factTr:'Mavi balina dünyanın en büyük canlısıdır ve bir otobüs kadar büyüktür!',
 factEn:'The blue whale is the largest animal on Earth, as big as a bus!',
 funFactTr:'Balina kalbi bir araba kadar büyüktür!',
 funFactEn:'A whale\'s heart is as big as a car!',
  },
  'deniz-02': {
    emoji: '🐬',
 factTr:'Yunuslar çok zeki hayvanlardır ve birbirleriyle konuşurlar!',
 factEn:'Dolphins are very smart animals and communicate with each other!',
 funFactTr:'Yunuslar uyurken bir gözleri açık kalır!',
 funFactEn:'Dolphins sleep with one eye open!',
  },
  'deniz-03': {
    emoji: '🐙',
 factTr:'Ahtapotların 8 kolu ve 3 kalbi vardır!',
 factEn:'Octopuses have 8 arms and 3 hearts!',
 funFactTr:'Ahtapotlar renk değiştirerek saklanabilir!',
 funFactEn:'Octopuses can change color to hide!',
  },
  'deniz-04': {
    emoji: '🦈',
 factTr:'Deniz atları yavaş yüzen küçük balıklardır ve babaları bebekleri taşır!',
 factEn:'Seahorses are small slow-swimming fish, and the dads carry the babies!',
 funFactTr:'Deniz atları çift olunca birbirlerinin kuyruklarını tutarlar!',
 funFactEn:'Seahorse couples hold each other\'s tails!',
  },
  'deniz-05': {
    emoji: '🐢',
 factTr:'Deniz kaplumbağaları 100 yıldan fazla yaşayabilir!',
 factEn:'Sea turtles can live for over 100 years!',
 funFactTr:'Deniz kaplumbağaları doğdukları plaja yumurta bırakmak için geri dönerler!',
 funFactEn:'Sea turtles return to the beach where they were born to lay eggs!',
  },
  'deniz-06': {
    emoji: '🦀',
 factTr:'Yengeçler yana doğru yürürler ve güçlü kıskaçları vardır!',
 factEn:'Crabs walk sideways and have strong pincers!',
 funFactTr:'Yengeçler büyüdükçe kabuklarını değiştirirler!',
 funFactEn:'Crabs change their shells as they grow!',
  },
  'deniz-07': {
    emoji: '🪼',
 factTr:'Denizanaları 500 milyon yıldır yaşıyorlar, dinozorlardan bile eskiler!',
 factEn:'Jellyfish have been around for 500 million years, even older than dinosaurs!',
 funFactTr:'Denizanalarının beyni yoktur!',
 funFactEn:'Jellyfish don\'t have brains!',
  },
  'deniz-08': {
    emoji: '🦈',
 factTr:'Köpekbalıkları aslında insanlara saldırmayı sevmez, çoğu zararsızdır!',
 factEn:'Sharks don\'t actually like attacking humans, most are harmless!',
 funFactTr:'Köpekbalıkları ömürleri boyunca 30.000 diş değiştirir!',
 funFactEn:'Sharks replace about 30,000 teeth in their lifetime!',
  },
  'deniz-09': {
    emoji: '🧜‍♀️',
 factTr:'Deniz kızları masallarda yaşar ve hayal gücümüzün en güzel kahramanlarıdır!',
 factEn:'Mermaids live in fairy tales and are among the most beautiful heroes of our imagination!',
 funFactTr:'Dünyanın birçok kültüründe deniz kızı hikayeleri vardır!',
 funFactEn:'Many cultures around the world have mermaid stories!',
  },
  'deniz-10': {
    emoji: '⭐',
 factTr:'Deniz yıldızları aslında balık değildir ve kolları kesilirse yeniden büyür!',
 factEn:'Starfish are not actually fish, and their arms grow back if cut off!',
 funFactTr:'Deniz yıldızlarının gözleri kollarının ucundadır!',
 funFactEn:'Starfish have eyes at the tips of their arms!',
  },
  // ===== MASALLAR =====
  'masallar-01': {
    emoji: '👸',
 factTr:'Prensesler masallarda cesur ve akıllı kahramanlardır!',
 factEn:'Princesses in fairy tales are brave and clever heroes!',
 funFactTr:'Dünyanın en eski masalı 4.000 yıl öncesine dayanır!',
 funFactEn:'The oldest fairy tale in the world is over 4,000 years old!',
  },
  'masallar-02': {
    emoji: '🏰',
 factTr:'Gerçek kaleler taştan yapılırdı ve içinde yüzlerce kişi yaşardı!',
 factEn:'Real castles were made of stone and hundreds of people lived inside!',
 funFactTr:'Dünyadaki en büyük kale Çek Cumhuriyeti\'ndedir!',
 funFactEn:'The largest castle in the world is in the Czech Republic!',
  },
  'masallar-03': {
    emoji: '🐉',
 factTr:'Ejderhalar masallarda yaşar ve hayal gücümüzün en harika yaratıklarıdır!',
 factEn:'Dragons live in fairy tales and are the most amazing creatures of our imagination!',
 funFactTr:'Çin\'de ejderhalar şans ve güç sembolüdür!',
 funFactEn:'In China, dragons are symbols of luck and power!',
  },
  'masallar-04': {
    emoji: '🦄',
 factTr:'Unicornlar (tek boynuzlu atlar) sihirli masallarda yaşayan güzel canlılardır!',
 factEn:'Unicorns are beautiful magical creatures that live in fairy tales!',
 funFactTr:'İskoçya\'nın ulusal hayvanı unicorndur!',
 funFactEn:'Scotland\'s national animal is the unicorn!',
  },
  'masallar-05': {
    emoji: '🧚',
 factTr:'Periler masallarda sihirli güçleri olan minik canlılardır!',
 factEn:'Fairies are tiny magical beings with special powers in fairy tales!',
 funFactTr:'İrlanda\'da hala peri kapıları yapılır ve bahçelere konulur!',
 funFactEn:'In Ireland, people still make fairy doors for their gardens!',
  },
  'masallar-06': {
    emoji: '⚔️',
 factTr:'Şövalyeler zırh giyer, at sürer ve krallarını korurdu!',
 factEn:'Knights wore armor, rode horses, and protected their kings!',
 funFactTr:'Bir şövalye zırhının ağırlığı 25 kg kadardı!',
 funFactEn:'A knight\'s armor weighed about 25 kg!',
  },
  'masallar-07': {
    emoji: '🧙',
 factTr:'Büyücüler masallarda sihirli güçleriyle harikalar yaratır!',
 factEn:'Wizards create wonders with their magical powers in fairy tales!',
 funFactTr:'Masallardaki en ünlü büyücü Merlin\'dir!',
 funFactEn:'The most famous wizard in fairy tales is Merlin!',
  },
  'masallar-08': {
    emoji: '👑',
 factTr:'Taçlar altın ve değerli taşlardan yapılır ve krallığı temsil eder!',
 factEn:'Crowns are made of gold and precious stones and represent royalty!',
 funFactTr:'İngiltere Kraliyet Tacı\'nda 2.868 elmas vardır!',
 funFactEn:'The British Crown has 2,868 diamonds!',
  },
  'masallar-09': {
    emoji: '🪄',
 factTr:'Sihirli lamba masalında Alaaddin\'in cin çağıran lambası vardır!',
 factEn:'In the fairy tale, Aladdin has a magical lamp that summons a genie!',
 funFactTr:'1001 Gece Masalları 1.000 yıldan eski hikayeler içerir!',
 funFactEn:'The 1001 Nights tales contain stories over 1,000 years old!',
  },
  'masallar-10': {
    emoji: '🏴‍☠️',
 factTr:'Korsanlar denizlerde macera yaşayan cesur denizcilerdir!',
 factEn:'Pirates were brave sailors who had adventures on the seas!',
 funFactTr:'Korsanlar göz bandını karanlığa alışmak için takardı!',
 funFactEn:'Pirates wore eye patches to adjust to darkness below deck!',
  },
  // ===== ARAÇLAR =====
  'araclar-01': {
    emoji: '🚗',
 factTr:'İlk otomobil 1886 yılında Almanya\'da Karl Benz tarafından yapıldı!',
 factEn:'The first car was made in 1886 in Germany by Karl Benz!',
 funFactTr:'Dünyadaki arabaların ortalama ömrü 12 yıldır!',
 funFactEn:'The average lifespan of a car is 12 years!',
  },
  'araclar-02': {
    emoji: '🚛',
 factTr:'Kamyonlar ağır yükleri uzun mesafelere taşırlar!',
 factEn:'Trucks carry heavy loads over long distances!',
 funFactTr:'Dünyanın en büyük kamyonu bir ev kadar büyüktür!',
 funFactEn:'The biggest truck in the world is as big as a house!',
  },
  'araclar-03': {
    emoji: '✈️',
 factTr:'Uçaklar gökyüzünde kuşlardan bile yüksekte uçar!',
 factEn:'Airplanes fly higher in the sky than even birds!',
 funFactTr:'Wright Kardeşler ilk uçuşu 1903\'te gerçekleştirdi!',
 funFactEn:'The Wright Brothers made the first flight in 1903!',
  },
  'araclar-04': {
    emoji: '🚂',
 factTr:'Trenler raylarda gider ve bir seferde yüzlerce yolcu taşıyabilir!',
 factEn:'Trains run on rails and can carry hundreds of passengers at once!',
 funFactTr:'Japonya\'daki hızlı tren saatte 320 km hıza ulaşır!',
 funFactEn:'Japan\'s bullet train reaches speeds of 320 km per hour!',
  },
  'araclar-05': {
    emoji: '🚁',
 factTr:'Helikopterler havada sabit durabilir ve dikey olarak inip kalkabilir!',
 factEn:'Helicopters can hover in the air and take off vertically!',
 funFactTr:'Leonardo da Vinci 500 yıl önce helikopter çizimi yapmıştı!',
 funFactEn:'Leonardo da Vinci drew a helicopter design 500 years ago!',
  },
  'araclar-06': {
    emoji: '🚢',
 factTr:'Büyük gemiler okyanusları geçebilir ve binlerce konteyner taşıyabilir!',
 factEn:'Big ships can cross oceans and carry thousands of containers!',
 funFactTr:'Dünyanın en büyük gemisi 4 futbol sahası uzunluğundadır!',
 funFactEn:'The biggest ship is as long as 4 football fields!',
  },
  'araclar-07': {
    emoji: '🚲',
 factTr:'Bisiklet çevre dostu bir ulaşım aracıdır ve egzersiz yapmamızı sağlar!',
 factEn:'Bicycles are eco-friendly transportation and help us exercise!',
 funFactTr:'Dünyada 1 milyardan fazla bisiklet vardır!',
 funFactEn:'There are over 1 billion bicycles in the world!',
  },
  'araclar-08': {
    emoji: '🚌',
 factTr:'Otobüsler şehirlerde insanları bir yerden başka yere taşır!',
 factEn:'Buses transport people from one place to another in cities!',
 funFactTr:'Londra\'nın kırmızı iki katlı otobüsleri çok ünlüdür!',
 funFactEn:'London\'s red double-decker buses are world famous!',
  },
  'araclar-09': {
    emoji: '🏍️',
 factTr:'Motosikletler iki tekerlek üzerinde giden hızlı araçlardır!',
 factEn:'Motorcycles are fast vehicles that ride on two wheels!',
 funFactTr:'İlk motosiklet 1885 yılında yapıldı!',
 funFactEn:'The first motorcycle was made in 1885!',
  },
  'araclar-10': {
    emoji: '🚒',
 factTr:'İtfaiye araçları yangınlara çok hızlı ulaşır ve insanları kurtarır!',
 factEn:'Fire trucks reach fires very quickly and rescue people!',
 funFactTr:'İtfaiyeciler yangın söndürme eğitiminde gerçek ateşle çalışır!',
 funFactEn:'Firefighters train with real fire to learn how to put out fires!',
  },
  // ===== DOĞA =====
  'doga-01': {
    emoji: '🌸',
 factTr:'Dünyada 400.000\'den fazla çiçek türü vardır ve kelebekler çiçekleri sever!',
 factEn:'There are over 400,000 flower species in the world and butterflies love flowers!',
 funFactTr:'Ayçiçekleri her zaman güneşe doğru döner!',
 funFactEn:'Sunflowers always turn toward the sun!',
  },
  'doga-02': {
    emoji: '🌳',
 factTr:'Ağaçlar bize nefes almamız için oksijen verir ve havayı temizler!',
 factEn:'Trees give us oxygen to breathe and clean the air!',
 funFactTr:'Dünyanın en yaşlı ağacı 5.000 yıldan fazladır!',
 funFactEn:'The oldest tree in the world is over 5,000 years old!',
  },
  'doga-03': {
    emoji: '🌈',
 factTr:'Gökkuşağı güneş ışığının yağmur damlalarından geçmesiyle oluşur!',
 factEn:'Rainbows form when sunlight passes through raindrops!',
 funFactTr:'Gökkuşağında 7 renk vardır: kırmızı, turuncu, sarı, yeşil, mavi, çivit, mor!',
 funFactEn:'A rainbow has 7 colors: red, orange, yellow, green, blue, indigo, violet!',
  },
  'doga-04': {
    emoji: '⛰️',
 factTr:'Everest Dağı dünyanın en yüksek noktasıdır, 8.849 metre yüksekliğindedir!',
 factEn:'Mount Everest is the highest point on Earth at 8,849 meters!',
 funFactTr:'Dağların tepesinde kar hiç erimez!',
 funFactEn:'Snow on top of mountains never melts!',
  },
  'doga-05': {
    emoji: '💧',
 factTr:'Şelaleler nehirlerin uçurumdan aşağı düşmesiyle oluşur ve çok güzeldir!',
 factEn:'Waterfalls form when rivers fall off cliffs and they are very beautiful!',
 funFactTr:'Dünyanın en yüksek şelalesi 979 metredir!',
 funFactEn:'The tallest waterfall in the world is 979 meters!',
  },
  'doga-06': {
    emoji: '🍄',
 factTr:'Mantarlar ne bitki ne de hayvan, ayrı bir canlı grubundadır!',
 factEn:'Mushrooms are neither plants nor animals, they are a separate group!',
 funFactTr:'Dünyanın en büyük canlısı bir mantar ağıdır!',
 funFactEn:'The largest living thing in the world is a mushroom network!',
  },
  'doga-07': {
    emoji: '🍂',
 factTr:'Sonbaharda yapraklar yeşilden sarıya ve kırmızıya döner!',
 factEn:'In autumn, leaves change from green to yellow and red!',
 funFactTr:'Yapraklar renklerini klorofil azaldığı için değiştirir!',
 funFactEn:'Leaves change color because chlorophyll decreases!',
  },
  'doga-08': {
    emoji: '🌹',
 factTr:'Güller en popüler çiçeklerden biridir ve 30.000\'den fazla çeşidi vardır!',
 factEn:'Roses are one of the most popular flowers with over 30,000 varieties!',
 funFactTr:'En eski gül fosili 35 milyon yıl öncesine aittir!',
 funFactEn:'The oldest rose fossil is 35 million years old!',
  },
  'doga-09': {
    emoji: '🌻',
 factTr:'Ayçiçekleri güneşi takip eder ve çekirdekleri çok lezzetlidir!',
 factEn:'Sunflowers follow the sun and their seeds are very tasty!',
 funFactTr:'Bir ayçiçeğinde 2.000\'e kadar çekirdek olabilir!',
 funFactEn:'A sunflower can have up to 2,000 seeds!',
  },
  'doga-10': {
    emoji: '🌲',
 factTr:'Ormanlar dünyamızın ciğerleridir ve birçok hayvan ormanda yaşar!',
 factEn:'Forests are the lungs of our planet and many animals live in forests!',
 funFactTr:'Amazon Ormanı dünya oksijeninin %20\'sini üretir!',
 funFactEn:'The Amazon Forest produces 20% of the world\'s oxygen!',
  },
  // ===== DİNOZORLAR =====
  'dinozorlar-01': {
    emoji: '🦖',
 factTr:'T-Rex en güçlü yırtıcı dinozorlardan biriydi ve 12 metre uzunluğundaydı!',
 factEn:'T-Rex was one of the strongest predator dinosaurs and was 12 meters long!',
 funFactTr:'T-Rex\'in kolları çok kısa ama ısırığı çok güçlüydü!',
 funFactEn:'T-Rex had very short arms but an incredibly powerful bite!',
  },
  'dinozorlar-02': {
    emoji: '🦕',
 factTr:'Triceratops üç boynuzlu bir dinozordur ve otçuldu!',
 factEn:'Triceratops had three horns and was a herbivore!',
 funFactTr:'Triceratops\'un kafası bir araba kadar büyüktü!',
 funFactEn:'Triceratops\' head was as big as a car!',
  },
  'dinozorlar-03': {
    emoji: '🦕',
 factTr:'Stegosaurus sırtındaki plakalarıyla tanınır ve otçul bir dinozordu!',
 factEn:'Stegosaurus is known for the plates on its back and was a herbivore!',
 funFactTr:'Stegosaurus\'un beyni bir ceviz kadar küçüktü!',
 funFactEn:'Stegosaurus had a brain the size of a walnut!',
  },
  'dinozorlar-04': {
    emoji: '🦅',
 factTr:'Pterodactyl uçabilen bir sürüngendi ama aslında dinozor değildi!',
 factEn:'Pterodactyl was a flying reptile but was not actually a dinosaur!',
 funFactTr:'Kanat açıklığı 10 metreden fazla olabilirdi!',
 funFactEn:'Its wingspan could be over 10 meters!',
  },
  'dinozorlar-05': {
    emoji: '🦕',
 factTr:'Brontosaurus çok uzun boyunlu bir dinozordu ve yaprak yerdi!',
 factEn:'Brontosaurus had a very long neck and ate leaves!',
 funFactTr:'Brontosaurus 22 metre uzunluğundaydı, 4 otobüs kadar!',
 funFactEn:'Brontosaurus was 22 meters long, like 4 buses!',
  },
  'dinozorlar-06': {
    emoji: '🦖',
 factTr:'Velociraptor küçük ama çok hızlı bir yırtıcıydı!',
 factEn:'Velociraptor was small but a very fast predator!',
 funFactTr:'Velociraptor aslında tüylüydü, filmlerdeki gibi değildi!',
 funFactEn:'Velociraptor actually had feathers, unlike in movies!',
  },
  'dinozorlar-07': {
    emoji: '🥚',
 factTr:'Dinozorlar yumurtadan doğardı, tıpkı kuşlar ve kaplumbağalar gibi!',
 factEn:'Dinosaurs hatched from eggs, just like birds and turtles!',
 funFactTr:'Bulunan en büyük dinozor yumurtası 30 cm uzunluğundaydı!',
 funFactEn:'The largest dinosaur egg found was 30 cm long!',
  },
  'dinozorlar-08': {
    emoji: '🌋',
 factTr:'Yanardağlar yeraltındaki sıcak kayanın yeryüzüne çıkmasıyla oluşur!',
 factEn:'Volcanoes form when hot underground rock rises to the surface!',
 funFactTr:'Dünyada 1.500\'den fazla aktif yanardağ vardır!',
 funFactEn:'There are over 1,500 active volcanoes on Earth!',
  },
  'dinozorlar-09': {
    emoji: '🦕',
 factTr:'Yavru dinozorlar anne babalarının bakımıyla büyürdü!',
 factEn:'Baby dinosaurs grew up with the care of their parents!',
 funFactTr:'Bazı yavru dinozorlar doğduklarında bir kedi kadardı!',
 funFactEn:'Some baby dinosaurs were as small as a cat when born!',
  },
  'dinozorlar-10': {
    emoji: '🦕',
 factTr:'Dinozorlar 165 milyon yıl boyunca dünyada yaşadı!',
 factEn:'Dinosaurs lived on Earth for 165 million years!',
 funFactTr:'İnsanlar sadece 300.000 yıldır varız, dinozorlar çok daha uzun yaşadı! ⏰',
 funFactEn:'Humans have been here only 300,000 years, dinosaurs lived much longer! ⏰',
  },
  // ===== YİYECEKLER =====
  'yiyecekler-01': {
    emoji: '🎂',
 factTr:'Doğum günü pastası geleneği eski Yunan\'da başladı!',
 factEn:'The birthday cake tradition started in ancient Greece!',
 funFactTr:'Dünyanın en büyük pastası 58 metre uzunluğundaydı!',
 funFactEn:'The world\'s largest cake was 58 meters long!',
  },
  'yiyecekler-02': {
    emoji: '🍦',
 factTr:'Dondurma yaklaşık 2.000 yıl önce Çin\'de icat edildi!',
 factEn:'Ice cream was invented in China about 2,000 years ago!',
 funFactTr:'En popüler dondurma aroması vanilyaadır!',
 funFactEn:'The most popular ice cream flavor is vanilla!',
  },
  'yiyecekler-03': {
    emoji: '🍕',
 factTr:'Pizza İtalya\'dan gelir ve dünyada en sevilen yiyeceklerden biridir!',
 factEn:'Pizza comes from Italy and is one of the most loved foods in the world!',
 funFactTr:'Dünyada her saniye 350 dilim pizza yenir!',
 funFactEn:'350 slices of pizza are eaten every second worldwide!',
  },
  'yiyecekler-04': {
    emoji: '🍎',
 factTr:'Meyveler vücudumuz için çok faydalıdır ve bizi güçlü yapar!',
 factEn:'Fruits are very good for our body and make us strong!',
 funFactTr:'Çilekler aslında meyve değil, aksesuar meyvedir!',
 funFactEn:'Strawberries aren\'t actually berries!',
  },
  'yiyecekler-05': {
    emoji: '🧁',
 factTr:'Cupcake\'ler küçük porsiyonluk pastacıklardır ve süslenmesi çok eğlencelidir!',
 factEn:'Cupcakes are small portion cakes and decorating them is very fun!',
 funFactTr:'İlk cupcake tarifi 1796 yılına aittir!',
 funFactEn:'The first cupcake recipe dates back to 1796!',
  },
  'yiyecekler-06': {
    emoji: '🍪',
 factTr:'Kurabiye Farsça "küçük kek" anlamına gelir!',
 factEn:'Cookie comes from the Dutch word "koekje" meaning "little cake"!',
 funFactTr:'Çikolatalı kurabiye aslında yanlışlıkla icat edildi!',
 funFactEn:'Chocolate chip cookies were invented by accident!',
  },
  'yiyecekler-07': {
    emoji: '🍩',
 factTr:'Donut ortasındaki delik hamuru eşit pişirmek için yapılır!',
 factEn:'The hole in a donut is made so the dough cooks evenly!',
 funFactTr:'Amerika\'da her yıl 10 milyar donut yenir!',
 funFactEn:'Americans eat 10 billion donuts every year!',
  },
  'yiyecekler-08': {
    emoji: '🍬',
 factTr:'Şekerler eski zamanlarda bal ve meyvelerden yapılırdı!',
 factEn:'In ancient times, candies were made from honey and fruits!',
 funFactTr:'Pamuk şeker aslında bir diş doktoru tarafından icat edildi!',
 funFactEn:'Cotton candy was actually invented by a dentist!',
  },
  'yiyecekler-09': {
    emoji: '🍔',
 factTr:'Hamburger adını Almanya\'daki Hamburg şehrinden alır!',
 factEn:'The hamburger gets its name from the city of Hamburg in Germany!',
 funFactTr:'Dünyanın en pahalı hamburgeri 5.000 dolar!',
 funFactEn:'The most expensive hamburger in the world costs $5,000!',
  },
  'yiyecekler-10': {
    emoji: '🍉',
 factTr:'Karpuz %92 sudan oluşur ve yaz aylarında çok serinleticidir!',
 factEn:'Watermelon is 92% water and is very refreshing in summer!',
 funFactTr:'Dünyanın en ağır karpuzu 159 kg geldi!',
 funFactEn:'The heaviest watermelon in the world weighed 159 kg!',
  },
  // ===== ŞEHİR =====
  'sehir-01': {
    emoji: '🏠',
 factTr:'Evler bizi sıcak tutar, yağmurdan korur ve güvende hissettirir!',
 factEn:'Houses keep us warm, protect us from rain, and make us feel safe!',
 funFactTr:'Dünyadaki en küçük ev sadece 1 metrekare!',
 funFactEn:'The smallest house in the world is only 1 square meter!',
  },
  'sehir-02': {
    emoji: '🏢',
 factTr:'Gökdelenler çok yüksek binalardır ve yüzlerce kat olabilir!',
 factEn:'Skyscrapers are very tall buildings and can have hundreds of floors!',
 funFactTr:'Dünyanın en yüksek binası 828 metredir!',
 funFactEn:'The tallest building in the world is 828 meters!',
  },
  'sehir-03': {
    emoji: '🏫',
 factTr:'Okullar öğrenmenin ve arkadaşlıkların kurulduğu harika yerlerdir!',
 factEn:'Schools are wonderful places where we learn and make friends!',
 funFactTr:'Dünyanın en eski okulu 1.000 yıldan fazladır!',
 funFactEn:'The oldest school in the world is over 1,000 years old!',
  },
  'sehir-04': {
    emoji: '🎢',
 factTr:'Oyun parkları eğlence, spor ve arkadaşlarla vakit geçirmek içindir!',
 factEn:'Playgrounds are for fun, exercise, and spending time with friends!',
 funFactTr:'Salıncak 5.000 yıldan fazladır çocukların favorisi!',
 funFactEn:'Swings have been children\'s favorite for over 5,000 years!',
  },
  'sehir-05': {
    emoji: '🌳',
 factTr:'Parklar şehirlerde doğayla buluştuğumuz yeşil alanlardır!',
 factEn:'Parks are green spaces in cities where we connect with nature!',
 funFactTr:'New York\'taki Central Park\'ta 25.000\'den fazla ağaç vardır!',
 funFactEn:'Central Park in New York has over 25,000 trees!',
  },
  'sehir-06': {
    emoji: '🌉',
 factTr:'Köprüler nehirlerin ve vadilerin üstünden geçmemizi sağlar!',
 factEn:'Bridges help us cross over rivers and valleys!',
 funFactTr:'Dünyanın en uzun köprüsü 164 km\'dir!',
 funFactEn:'The longest bridge in the world is 164 km!',
  },
  'sehir-07': {
    emoji: '🏮',
 factTr:'Deniz fenerleri gemilere yol gösterir ve onları kayalıklardan korur!',
 factEn:'Lighthouses guide ships and protect them from rocks!',
 funFactTr:'En eski deniz feneri 2.300 yıl öncesine aittir!',
 funFactEn:'The oldest lighthouse dates back 2,300 years!',
  },
  'sehir-08': {
    emoji: '🌾',
 factTr:'Yel değirmenleri rüzgarın gücünü kullanarak tahıl öğütür!',
 factEn:'Windmills use wind power to grind grain!',
 funFactTr:'Hollanda dünyaca ünlü yel değirmenleriyle tanınır!',
 funFactEn:'The Netherlands is famous for its windmills!',
  },
  'sehir-09': {
    emoji: '🐄',
 factTr:'Çiftlikler yiyeceklerimizin yetiştirildiği ve hayvanların bakıldığı yerlerdir!',
 factEn:'Farms are where our food is grown and animals are cared for!',
 funFactTr:'Bir inek günde 200 litre süt verebilir!',
 funFactEn:'A cow can produce 200 liters of milk per day!',
  },
  'sehir-10': {
    emoji: '🚉',
 factTr:'Tren istasyonları insanların trenlere binip indiği yerlerdir!',
 factEn:'Train stations are where people board and exit trains!',
 funFactTr:'Dünyanın en işlek istasyonu Tokyo\'daki Shinjuku\'dur!',
 funFactEn:'The busiest station in the world is Shinjuku in Tokyo!',
  },
  // ===== TATİL =====
  'tatil-01': {
    emoji: '🎄',
 factTr:'Noel ağacı süsleme geleneği 500 yıl öncesine dayanır!',
 factEn:'The tradition of decorating Christmas trees dates back 500 years!',
 funFactTr:'Her yıl dünyada 35 milyon Noel ağacı satılır!',
 funFactEn:'35 million Christmas trees are sold worldwide every year!',
  },
  'tatil-02': {
    emoji: '🎃',
 factTr:'Cadılar Bayramı\'nda çocuklar kostüm giyer ve şeker toplar!',
 factEn:'On Halloween, children wear costumes and collect candy!',
 funFactTr:'En ağır balkabağı 1.190 kg geldi!',
 funFactEn:'The heaviest pumpkin weighed 1,190 kg!',
  },
  'tatil-03': {
    emoji: '🐣',
 factTr:'Paskalya baharın gelişini kutlayan renkli bir bayramdır!',
 factEn:'Easter is a colorful holiday celebrating the arrival of spring!',
 funFactTr:'Dünyanın en büyük Paskalya yumurtası 10 metre yüksekliğindeydi!',
 funFactEn:'The largest Easter egg was 10 meters tall!',
  },
  'tatil-04': {
    emoji: '🎂',
 factTr:'Doğum günleri her yıl bir yaş büyüdüğümüzü kutladığımız özel günlerdir!',
 factEn:'Birthdays are special days when we celebrate growing one year older!',
 funFactTr:'En çok doğum günü Eylül ayında kutlanır!',
 funFactEn:'September has the most birthdays of any month!',
  },
  'tatil-05': {
    emoji: '⛄',
 factTr:'Kardan adam yapmak kış mevsiminin en eğlenceli aktivitesidir!',
 factEn:'Building a snowman is the most fun activity of winter!',
 funFactTr:'Dünyanın en büyük kardan adamı 37 metre yüksekliğindeydi!',
 funFactEn:'The tallest snowman ever was 37 meters tall!',
  },
  'tatil-06': {
    emoji: '🎅',
 factTr:'Noel Baba çocuklara hediye getiren neşeli ve sevilen bir karakterdir!',
 factEn:'Santa Claus is a cheerful and beloved character who brings gifts to children!',
 funFactTr:'Noel Baba\'nın ren geyiklerinin hepsinin isimleri vardır!',
 funFactEn:'All of Santa\'s reindeer have names!',
  },
  'tatil-07': {
    emoji: '🎃',
 factTr:'Balkabağı hem yiyecek hem de dekorasyon olarak kullanılır!',
 factEn:'Pumpkins are used both as food and as decorations!',
 funFactTr:'Balkabağı aslında bir meyvedir, sebze değil!',
 funFactEn:'Pumpkins are actually fruits, not vegetables!',
  },
  'tatil-08': {
    emoji: '❤️',
 factTr:'Sevgililer Günü\'nde insanlar sevdiklerine kart ve çiçek verir!',
 factEn:'On Valentine\'s Day, people give cards and flowers to their loved ones!',
 funFactTr:'Her yıl 1 milyardan fazla Sevgililer Günü kartı gönderilir!',
 funFactEn:'Over 1 billion Valentine\'s Day cards are sent every year!',
  },
  'tatil-09': {
    emoji: '🎆',
 factTr:'Havai fişekler kutlamalarda gökyüzünü rengarenk yapar!',
 factEn:'Fireworks make the sky colorful during celebrations!',
 funFactTr:'Havai fişek 2.000 yıl önce Çin\'de icat edildi!',
 funFactEn:'Fireworks were invented in China 2,000 years ago!',
  },
  'tatil-10': {
    emoji: '🎁',
 factTr:'Hediye vermek sevgi göstermenin en güzel yollarından biridir!',
 factEn:'Giving gifts is one of the most beautiful ways to show love!',
 funFactTr:'Hediye ambalaj kağıdı 1917 yılında icat edildi!',
 funFactEn:'Gift wrapping paper was invented in 1917!',
  },
  // ===== ALFABE =====
  'alfabe-A': { emoji: '🦁', factTr: 'A alfabenin ilk harfidir! Aslan kelimesi A ile başlar.', factEn: 'A is the first letter of the alphabet! Lion starts with L in English.', funFactTr: 'Türkçede en çok kullanılan harf A harfidir!', funFactEn: 'A is one of the most common letters in many languages!' },
  'alfabe-B': { emoji: '🎈', factTr: 'B harfi ile Balon kelimesi başlar! Balonlar uçar.', factEn: 'B is for Balloon! Balloons can float in the air.', funFactTr: 'İlk balonlar hayvan derisinden yapılmıştı!', funFactEn: 'The first balloons were made from animal bladders!' },
  'alfabe-C': { emoji: '👛', factTr: 'C harfi ile Cüzdan kelimesi başlar!', factEn: 'C is for Wallet! We keep our money safe in wallets.', funFactTr: 'Dünyadaki en eski para 2.700 yıl öncesine aittir!', funFactEn: 'The oldest coins in the world are 2,700 years old!' },
  'alfabe-Ç': { emoji: '🌸', factTr: 'Ç harfi ile Çiçek kelimesi başlar! Çiçekler çok güzel kokar.', factEn: 'Ç is for Flower! Flowers smell wonderful.', funFactTr: 'Dünyada 400.000den fazla çiçek türü vardır!', funFactEn: 'There are over 400,000 species of flowers in the world!' },
  'alfabe-D': { emoji: '🥁', factTr: 'D harfi ile Davul kelimesi başlar! Davul en eski müzik aletlerinden biridir.', factEn: 'D is for Drum! Drums are one of the oldest musical instruments.', funFactTr: 'Davullar 6.000 yıldan fazladır kullanılıyor!', funFactEn: 'Drums have been used for over 6,000 years!' },
  'alfabe-E': { emoji: '🍎', factTr: 'E harfi ile Elma kelimesi başlar! Elmalar çok sağlıklıdır.', factEn: 'E is for Apple! Apples are very healthy.', funFactTr: 'Dünyada 7.500den fazla elma çeşidi vardır!', funFactEn: 'There are over 7,500 varieties of apples in the world!' },
  'alfabe-F': { emoji: '🐘', factTr: 'F harfi ile Fil kelimesi başlar! Filler çok büyük ve akıllıdır.', factEn: 'F is for Elephant! Elephants are big and smart.', funFactTr: 'Filler birbirlerine sarılarak selamlaşır!', funFactEn: 'Elephants greet each other by wrapping their trunks together!' },
  'alfabe-G': { emoji: '🚢', factTr: 'G harfi ile Gemi kelimesi başlar! Gemiler denizlerde yolculuk yapar.', factEn: 'G is for Ship! Ships travel across the seas.', funFactTr: 'En büyük gemiler 4 futbol sahası uzunluğundadır!', funFactEn: 'The largest ships are as long as 4 football fields!' },
  'alfabe-G-soft': { emoji: '🔤', factTr: 'Ğ harfi Türkçeye özel bir harftir! Yumuşak G olarak bilinir.', factEn: 'Ğ is a special letter unique to Turkish! It is called soft G.', funFactTr: 'Ğ harfi hiçbir kelimenin başında kullanılmaz!', funFactEn: 'The letter Ğ is never used at the beginning of a word!' },
  'alfabe-H': { emoji: '🐓', factTr: 'H harfi ile Horoz kelimesi başlar! Horozlar sabah erken öter.', factEn: 'H is for Rooster! Roosters crow early in the morning.', funFactTr: 'Horozlar güneş doğmadan önce öter!', funFactEn: 'Roosters crow before the sun rises!' },
  'alfabe-I': { emoji: '🦎', factTr: 'I harfi ile Iguana kelimesi başlar! İguanalar tropikal bölgelerde yaşar.', factEn: 'I is for Iguana! Iguanas live in tropical regions.', funFactTr: 'İguanalar 20 yıla kadar yaşayabilir!', funFactEn: 'Iguanas can live up to 20 years!' },
  'alfabe-I-dot': { emoji: '🐄', factTr: 'İ harfi ile İnek kelimesi başlar! İnekler bize süt verir.', factEn: 'İ is for Cow! Cows give us milk.', funFactTr: 'Bir inek günde 200 litre süt üretebilir!', funFactEn: 'A cow can produce up to 200 liters of milk per day!' },
  'alfabe-J': { emoji: '🚙', factTr: 'J harfi ile Jip kelimesi başlar! Jipler her arazide gidebilir.', factEn: 'J is for Jeep! Jeeps can go on any terrain.', funFactTr: 'İlk jip 1940 yılında askeri amaçla yapıldı!', funFactEn: 'The first jeep was made in 1940 for military use!' },
  'alfabe-K': { emoji: '🐱', factTr: 'K harfi ile Kedi kelimesi başlar! Kediler çok sevimli hayvanlardır.', factEn: 'K is for Cat! Cats are very cute animals.', funFactTr: 'Kediler günde 16 saat uyuyabilir!', funFactEn: 'Cats can sleep up to 16 hours a day!' },
  'alfabe-L': { emoji: '🌷', factTr: 'L harfi ile Lale kelimesi başlar! Laleler baharın simgesidir.', factEn: 'L is for Tulip! Tulips are a symbol of spring.', funFactTr: 'Laleler aslında Türkiyeden dünyaya yayılmıştır!', funFactEn: 'Tulips originally spread from Turkey to the world!' },
  'alfabe-M': { emoji: '🐵', factTr: 'M harfi ile Maymun kelimesi başlar! Maymunlar ağaçlarda yaşar.', factEn: 'M is for Monkey! Monkeys live in trees.', funFactTr: 'Maymunlar muzları insanlar gibi soyar!', funFactEn: 'Monkeys peel bananas just like humans!' },
  'alfabe-N': { emoji: '🍎', factTr: 'N harfi ile Nar kelimesi başlar! Narlar içi kırmızı taneli meyvedir.', factEn: 'N is for Pomegranate! Pomegranates have red seeds inside.', funFactTr: 'Bir narda yaklaşık 600 tane bulunur!', funFactEn: 'A pomegranate contains about 600 seeds!' },
  'alfabe-O': { emoji: '🚌', factTr: 'O harfi ile Otobüs kelimesi başlar! Otobüsler insanları taşır.', factEn: 'O is for Bus! Buses carry people around the city.', funFactTr: 'Londrann kırmızı otobüsleri dünyaca ünlüdür!', funFactEn: 'Londons red buses are famous around the world!' },
  'alfabe-O-uml': { emoji: '🦆', factTr: 'Ö harfi ile Ördek kelimesi başlar! Ördekler hem yüzer hem uçar.', factEn: 'Ö is for Duck! Ducks can both swim and fly.', funFactTr: 'Ördeklerin ayakları soğuğu hissetmez!', funFactEn: 'Ducks feet dont feel the cold!' },
  'alfabe-P': { emoji: '🦜', factTr: 'P harfi ile Papağan kelimesi başlar! Papağanlar konuşmayı taklit edebilir.', factEn: 'P is for Parrot! Parrots can mimic speech.', funFactTr: 'Papağanlar 80 yıla kadar yaşayabilir!', funFactEn: 'Parrots can live up to 80 years!' },
  'alfabe-R': { emoji: '🤖', factTr: 'R harfi ile Robot kelimesi başlar! Robotlar bize yardım eder.', factEn: 'R is for Robot! Robots help us with tasks.', funFactTr: 'Robot kelimesi Çekçe zorunlu iş anlamına gelir!', funFactEn: 'The word robot comes from Czech meaning forced labor!' },
  'alfabe-S': { emoji: '🐌', factTr: 'S harfi ile Salyangoz kelimesi başlar! Salyangozlar çok yavaş hareket eder.', factEn: 'S is for Snail! Snails move very slowly.', funFactTr: 'Salyangozlar 3 yıla kadar uyuyabilir!', funFactEn: 'Snails can sleep for up to 3 years!' },
  'alfabe-S-ced': { emoji: '☂️', factTr: 'Ş harfi ile Şemsiye kelimesi başlar! Şemsiye bizi yağmurdan korur.', factEn: 'Ş is for Umbrella! Umbrellas protect us from rain.', funFactTr: 'Şemsiye 4.000 yıldan fazladır kullanılıyor!', funFactEn: 'Umbrellas have been used for over 4,000 years!' },
  'alfabe-T': { emoji: '🐰', factTr: 'T harfi ile Tavşan kelimesi başlar! Tavşanlar çok hızlı koşar.', factEn: 'T is for Rabbit! Rabbits can run very fast.', funFactTr: 'Tavşanların dişleri hiç büyümeyi durdurmaz!', funFactEn: 'Rabbits teeth never stop growing!' },
  'alfabe-U': { emoji: '✈️', factTr: 'U harfi ile Uçak kelimesi başlar! Uçaklar bulutların üstünde uçar.', factEn: 'U is for Airplane! Airplanes fly above the clouds.', funFactTr: 'Her gün dünyada 100.000den fazla uçuş yapılır!', funFactEn: 'Over 100,000 flights take place every day worldwide!' },
  'alfabe-U-uml': { emoji: '🍇', factTr: 'Ü harfi ile Üzüm kelimesi başlar! Üzümler salkım halinde büyür.', factEn: 'Ü is for Grapes! Grapes grow in bunches.', funFactTr: 'Dünyada 8.000den fazla üzüm çeşidi vardır!', funFactEn: 'There are over 8,000 grape varieties in the world!' },
  'alfabe-V': { emoji: '🏺', factTr: 'V harfi ile Vazo kelimesi başlar! Vazolara çiçek koyarız.', factEn: 'V is for Vase! We put flowers in vases.', funFactTr: 'En eski vazolar 20.000 yıl öncesine aittir!', funFactEn: 'The oldest vases date back 20,000 years!' },
  'alfabe-Y': { emoji: '⭐', factTr: 'Y harfi ile Yıldız kelimesi başlar! Yıldızlar gece gökyüzünde parlar.', factEn: 'Y is for Star! Stars shine in the night sky.', funFactTr: 'Gözle 5.000den fazla yıldız görebilirsin!', funFactEn: 'You can see over 5,000 stars with your eyes!' },
  'alfabe-Z': { emoji: '🦒', factTr: 'Z harfi ile Zürafa kelimesi başlar! Zürafalar en uzun hayvanlardır.', factEn: 'Z is for Giraffe! Giraffes are the tallest animals.', funFactTr: 'Zürafaların dili 50 cm uzunluğundadır!', funFactEn: 'A giraffes tongue is 50 cm long!' },
  // ===== SAYILAR =====
  'sayilar-01': { emoji: '1️⃣', factTr: '1 sayısı en küçük doğal sayıdır! Her şey birle başlar.', factEn: 'The number 1 is the smallest natural number! Everything starts with one.', funFactTr: 'Dünyada sadece 1 Güneş vardır!', funFactEn: 'There is only 1 Sun in our solar system!' },
  'sayilar-02': { emoji: '2️⃣', factTr: '2 sayısı tek çift sayıdır! Gözlerimiz, kulaklarımız ve ellerimiz 2 tanedir.', factEn: 'The number 2 is the only even prime number! We have 2 eyes, ears, and hands.', funFactTr: 'Kuğular genellikle 2li çift olarak yaşar!', funFactEn: 'Swans usually live in pairs of 2!' },
  'sayilar-03': { emoji: '3️⃣', factTr: '3 sayısı çok özel! Bir üçgenin 3 köşesi vardır.', factEn: 'The number 3 is special! A triangle has 3 corners.', funFactTr: 'Trafik ışığında 3 renk vardır: kırmızı, sarı, yeşil!', funFactEn: 'Traffic lights have 3 colors: red, yellow, green!' },
  'sayilar-04': { emoji: '4️⃣', factTr: '4 mevsim vardır: ilkbahar, yaz, sonbahar, kış!', factEn: 'There are 4 seasons: spring, summer, autumn, winter!', funFactTr: 'Bir köpeğin her patisinde 4 parmak vardır!', funFactEn: 'Dogs have 4 toes on each paw!' },
  'sayilar-05': { emoji: '5️⃣', factTr: 'Her elimizde 5 parmak vardır! 5 duyu organımız var: görme, duyma, koklama, tatma, dokunma.', factEn: 'We have 5 fingers on each hand! We have 5 senses.', funFactTr: 'Deniz yıldızlarının genellikle 5 kolu vardır!', funFactEn: 'Starfish usually have 5 arms!' },
  'sayilar-06': { emoji: '6️⃣', factTr: 'Arıların petek gözleri 6 köşelidir (altıgen)!', factEn: 'Honeycomb cells are 6-sided (hexagons)!', funFactTr: 'Kar taneleri her zaman 6 kolludur!', funFactEn: 'Snowflakes always have 6 arms!' },
  'sayilar-07': { emoji: '7️⃣', factTr: 'Gökkuşağında 7 renk vardır! Bir haftada 7 gün var.', factEn: 'A rainbow has 7 colors! There are 7 days in a week.', funFactTr: 'Müzikte 7 nota vardır: do, re, mi, fa, sol, la, si!', funFactEn: 'There are 7 musical notes: do, re, mi, fa, sol, la, si!' },
  'sayilar-08': { emoji: '8️⃣', factTr: 'Ahtapotların 8 kolu vardır! 8 sayısı yatırınca sonsuzluk işareti olur.', factEn: 'Octopuses have 8 arms! The number 8 sideways becomes the infinity symbol.', funFactTr: 'Örümceklerin de 8 bacağı vardır!', funFactEn: 'Spiders also have 8 legs!' },
  'sayilar-09': { emoji: '9️⃣', factTr: 'Kedilerin 9 canı olduğu söylenir! 9 en büyük tek basamaklı sayıdır.', factEn: 'Cats are said to have 9 lives! 9 is the largest single-digit number.', funFactTr: 'Güneş sistemindeki en büyük gezegen Jüpiterin 9 halkası var!', funFactEn: 'Jupiter, the largest planet, has 9 rings!' },
  'sayilar-10': { emoji: '🔟', factTr: '10 sayısı iki basamaklı ilk sayıdır! 10 parmağımız var.', factEn: 'The number 10 is the first two-digit number! We have 10 fingers.', funFactTr: 'Bowling oyununda 10 pin vardır!', funFactEn: 'There are 10 pins in bowling!' },
  // ===== GEZEGENLER =====
  'gezegenler-01': { emoji: '☀️', factTr: 'Güneş bir yıldızdır ve güneş sistemimizin merkezindedir!', factEn: 'The Sun is a star at the center of our solar system!', funFactTr: 'Güneşin içine 1 milyon Dünya sığar!', funFactEn: 'One million Earths could fit inside the Sun!' },
  'gezegenler-02': { emoji: '🪨', factTr: 'Merkür Güneşe en yakın gezegendir ve çok sıcaktır!', factEn: 'Mercury is the closest planet to the Sun and very hot!', funFactTr: 'Merkürde bir gün bir yıldan uzun sürer!', funFactEn: 'A day on Mercury is longer than its year!' },
  'gezegenler-03': { emoji: '🌫️', factTr: 'Venüs kalın bulutlarla kaplıdır ve en sıcak gezegendir!', factEn: 'Venus is covered in thick clouds and is the hottest planet!', funFactTr: 'Venüs ters yöne döner, güneş batıdan doğar!', funFactEn: 'Venus rotates backwards, so the sun rises in the west!' },
  'gezegenler-04': { emoji: '🌍', factTr: 'Dünya bizim evimizdir! Yaşam için mükemmel bir gezegendir.', factEn: 'Earth is our home! It is the perfect planet for life.', funFactTr: 'Dünya saniyede 30 km hızla Güneş etrafında döner!', funFactEn: 'Earth orbits the Sun at 30 km per second!' },
  'gezegenler-05': { emoji: '🔴', factTr: 'Mars kırmızı gezegen olarak bilinir! Yüzeyinde pas rengi toz vardır.', factEn: 'Mars is known as the red planet! Its surface has rust-colored dust.', funFactTr: 'Marsın en yüksek dağı Everestten 3 kat büyüktür!', funFactEn: 'Mars tallest mountain is 3 times taller than Everest!' },
  'gezegenler-06': { emoji: '🟤', factTr: 'Jüpiter güneş sistemindeki en büyük gezegendir!', factEn: 'Jupiter is the largest planet in our solar system!', funFactTr: 'Jüpiterin Büyük Kırmızı Lekesi 300 yıldan fazladır fırtına!', funFactEn: 'Jupiters Great Red Spot has been a storm for over 300 years!' },
  'gezegenler-07': { emoji: '🪐', factTr: 'Satürn güzel halkaları ile tanınır! Halkalar buz ve kayadan oluşur.', factEn: 'Saturn is known for its beautiful rings made of ice and rock!', funFactTr: 'Satürn o kadar hafif ki suda yüzebilir!', funFactEn: 'Saturn is so light it could float on water!' },
  'gezegenler-08': { emoji: '🔵', factTr: 'Uranüs yan yatmış dönen ilginç bir gezegendir!', factEn: 'Uranus is an interesting planet that rotates on its side!', funFactTr: 'Uranüste bir mevsim 21 yıl sürer!', funFactEn: 'One season on Uranus lasts 21 years!' },
  'gezegenler-09': { emoji: '💙', factTr: 'Neptün güneş sistemindeki en uzak gezegendir ve çok fırtınalıdır!', factEn: 'Neptune is the farthest planet and is very stormy!', funFactTr: 'Neptündeki rüzgarlar saatte 2.000 kmye ulaşır!', funFactEn: 'Winds on Neptune reach 2,000 km per hour!' },
  'gezegenler-10': { emoji: '🌙', factTr: 'Ay Dünya etrafında döner ve gecelerimizi aydınlatır!', factEn: 'The Moon orbits Earth and lights up our nights!', funFactTr: 'Ayda bırakılan ayak izleri sonsuza kadar kalır!', funFactEn: 'Footprints left on the Moon last forever!' },
  // ===== ENGLISH ALPHABET =====
  'alphabet-A': { emoji: '🍎', factTr: 'A İngilizce alfabenin ilk harfidir! Apple (elma) A ile başlar.', factEn: 'A is the first letter of the English alphabet! Apple starts with A.', funFactTr: 'İngilizce en çok kullanılan harf E harfidir!', funFactEn: 'The most used letter in English is E!' },
  'alphabet-B': { emoji: '⚽', factTr: 'B harfi ile Ball (top) kelimesi başlar!', factEn: 'B is for Ball! Balls are round and fun to play with.', funFactTr: 'Futbol dünyanın en popüler sporudur!', funFactEn: 'Soccer is the most popular sport in the world!' },
  'alphabet-C': { emoji: '🐱', factTr: 'C harfi ile Cat (kedi) kelimesi başlar!', factEn: 'C is for Cat! Cats purr when they are happy.', funFactTr: 'Kediler günde 16 saat uyuyabilir!', funFactEn: 'Cats can sleep up to 16 hours a day!' },
  'alphabet-D': { emoji: '🐶', factTr: 'D harfi ile Dog (köpek) kelimesi başlar!', factEn: 'D is for Dog! Dogs are loyal friends.', funFactTr: 'Köpekler 200 kelimeye kadar anlayabilir!', funFactEn: 'Dogs can understand up to 200 words!' },
  'alphabet-E': { emoji: '🐘', factTr: 'E harfi ile Elephant (fil) kelimesi başlar!', factEn: 'E is for Elephant! Elephants never forget.', funFactTr: 'Filler çok iyi hafızaya sahiptir!', funFactEn: 'Elephants have amazing memories!' },
  'alphabet-F': { emoji: '🐠', factTr: 'F harfi ile Fish (balık) kelimesi başlar!', factEn: 'F is for Fish! Fish breathe underwater using gills.', funFactTr: 'Okyanuslarda 30.000den fazla balık türü vardır!', funFactEn: 'There are over 30,000 species of fish in the oceans!' },
  'alphabet-G': { emoji: '🦒', factTr: 'G harfi ile Giraffe (zürafa) kelimesi başlar!', factEn: 'G is for Giraffe! Giraffes are the tallest animals.', funFactTr: 'Zürafaların dili 50 cm uzunluğundadır!', funFactEn: 'A giraffes tongue is 50 cm long!' },
  'alphabet-H': { emoji: '🏠', factTr: 'H harfi ile House (ev) kelimesi başlar!', factEn: 'H is for House! Houses keep us warm and safe.', funFactTr: 'Dünyadaki en küçük ev sadece 1 metrekare!', funFactEn: 'The smallest house in the world is just 1 square meter!' },
  'alphabet-I': { emoji: '🍦', factTr: 'I harfi ile Ice cream (dondurma) kelimesi başlar!', factEn: 'I is for Ice cream! Ice cream was invented about 2,000 years ago.', funFactTr: 'En popüler dondurma aroması vanilyaadır!', funFactEn: 'The most popular ice cream flavor is vanilla!' },
  'alphabet-J': { emoji: '🪼', factTr: 'J harfi ile Jellyfish (denizanası) kelimesi başlar!', factEn: 'J is for Jellyfish! Jellyfish have been around for millions of years.', funFactTr: 'Denizanalarının beyni yoktur!', funFactEn: 'Jellyfish dont have brains!' },
  'alphabet-K': { emoji: '🪁', factTr: 'K harfi ile Kite (uçurtma) kelimesi başlar!', factEn: 'K is for Kite! Kites were invented in China over 2,000 years ago.', funFactTr: 'Uçurtmalar ilk olarak Çinde icat edildi!', funFactEn: 'Kites were first invented in China!' },
  'alphabet-L': { emoji: '🦁', factTr: 'L harfi ile Lion (aslan) kelimesi başlar!', factEn: 'L is for Lion! Lions are called the king of animals.', funFactTr: 'Aslanlar günde 20 saat uyuyabilir!', funFactEn: 'Lions can sleep up to 20 hours a day!' },
  'alphabet-M': { emoji: '🐵', factTr: 'M harfi ile Monkey (maymun) kelimesi başlar!', factEn: 'M is for Monkey! Monkeys are very smart and playful.', funFactTr: 'Dünyada 260dan fazla maymun türü vardır!', funFactEn: 'There are over 260 species of monkeys in the world!' },
  'alphabet-N': { emoji: '🪺', factTr: 'N harfi ile Nest (yuva) kelimesi başlar!', factEn: 'N is for Nest! Birds build nests to keep their eggs safe.', funFactTr: 'En büyük kuş yuvası 3 metre genişliğindedir!', funFactEn: 'The largest bird nest is 3 meters wide!' },
  'alphabet-O': { emoji: '🍊', factTr: 'O harfi ile Orange (portakal) kelimesi başlar!', factEn: 'O is for Orange! Oranges are full of vitamin C.', funFactTr: 'Portakal rengi adını portakaldan alır, tersi değil!', funFactEn: 'The color orange is named after the fruit!' },
  'alphabet-P': { emoji: '🍕', factTr: 'P harfi ile Pizza kelimesi başlar!', factEn: 'P is for Pizza! Pizza was invented in Italy.', funFactTr: 'Dünyada her saniye 350 dilim pizza yenir!', funFactEn: '350 slices of pizza are eaten every second worldwide!' },
  'alphabet-Q': { emoji: '👑', factTr: 'Q harfi ile Queen (kraliçe) kelimesi başlar!', factEn: 'Q is for Queen! Queens wear crowns and rule kingdoms.', funFactTr: 'Q İngiliz alfabesinde en az kullanılan harflerden biridir!', funFactEn: 'Q is one of the least used letters in English!' },
  'alphabet-R': { emoji: '🐰', factTr: 'R harfi ile Rabbit (tavşan) kelimesi başlar!', factEn: 'R is for Rabbit! Rabbits hop and have long ears.', funFactTr: 'Tavşanlar mutlu olunca havada zıplar!', funFactEn: 'Rabbits jump in the air when they are happy!' },
  'alphabet-S': { emoji: '☀️', factTr: 'S harfi ile Sun (güneş) kelimesi başlar!', factEn: 'S is for Sun! The Sun gives us light and warmth every day.', funFactTr: 'Güneşin içine 1 milyon Dünya sığar!', funFactEn: 'One million Earths could fit inside the Sun!' },
  'alphabet-T': { emoji: '🌳', factTr: 'T harfi ile Tree (ağaç) kelimesi başlar!', factEn: 'T is for Tree! Trees give us oxygen to breathe.', funFactTr: 'En yaşlı ağaç 5.000 yıldan fazladır!', funFactEn: 'The oldest tree is over 5,000 years old!' },
  'alphabet-U': { emoji: '☂️', factTr: 'U harfi ile Umbrella (şemsiye) kelimesi başlar!', factEn: 'U is for Umbrella! Umbrellas protect us from rain.', funFactTr: 'Şemsiyeler 4.000 yıldan fazladır kullanılıyor!', funFactEn: 'Umbrellas have been used for over 4,000 years!' },
  'alphabet-V': { emoji: '🎻', factTr: 'V harfi ile Violin (keman) kelimesi başlar!', factEn: 'V is for Violin! The violin is a beautiful string instrument.', funFactTr: 'Keman 500 yıldan fazladır çalınmaktadır!', funFactEn: 'The violin has been played for over 500 years!' },
  'alphabet-W': { emoji: '🐋', factTr: 'W harfi ile Whale (balina) kelimesi başlar!', factEn: 'W is for Whale! Whales are the largest animals on Earth.', funFactTr: 'Mavi balina kalbi bir araba büyüklüğündedir!', funFactEn: 'A blue whales heart is as big as a car!' },
  'alphabet-X': { emoji: '🎵', factTr: 'X harfi ile Xylophone (ksilofon) kelimesi başlar!', factEn: 'X is for Xylophone! A xylophone makes beautiful musical sounds.', funFactTr: 'Ksilofon Yunanca ahşap ses anlamına gelir!', funFactEn: 'Xylophone means wood sound in Greek!' },
  'alphabet-Y': { emoji: '⛵', factTr: 'Y harfi ile Yacht (yat) kelimesi başlar!', factEn: 'Y is for Yacht! Yachts sail on the ocean.', funFactTr: 'En büyük yat 180 metreden uzundur!', funFactEn: 'The largest yacht is over 180 meters long!' },
  'alphabet-Z': { emoji: '🦓', factTr: 'Z harfi ile Zebra kelimesi başlar!', factEn: 'Z is for Zebra! Every zebra has unique stripes like fingerprints.', funFactTr: 'Her zebranın çizgileri parmak izi gibi benzersizdir!', funFactEn: 'Every zebras stripes are unique like fingerprints!' },
};
