export interface EducationalFact {
  emoji: string;
 factTr: string;
 factEn: string;
 funFactTr: string;
 funFactEn: string;
}

export const EDUCATIONAL_FACTS: Record<string, EducationalFact> = {
  // ===== HAYVANLAR =====
  'hayvanlar-01': {
    emoji: '🐱',
 factTr:'Kediler çok temiz hayvanlardır ve günün üçte birini kendilerini temizleyerek geçirirler!',
 factEn:'Cats are very clean animals and spend one-third of their day grooming themselves!',
 funFactTr:'Kediler 100\'den fazla farklı ses çıkarabilir!',
 funFactEn:'Cats can make over 100 different sounds!',
  },
  'hayvanlar-02': {
    emoji: '🐶',
 factTr:'Köpekler insanların en iyi arkadaşıdır ve 15.000 yıldır bizimle yaşıyorlar!',
 factEn:'Dogs are humans\' best friends and have lived with us for 15,000 years!',
 funFactTr:'Köpekler kokuyu insanlardan 10.000 kat daha iyi alabilir!',
 funFactEn:'Dogs can smell 10,000 times better than humans!',
  },
  'hayvanlar-03': {
    emoji: '🦁',
 factTr:'Aslanlar aslında ormanda değil, Afrika çayırlarında ve savanalarında yaşar!',
 factEn:'Lions actually live in African grasslands and savannas, not in jungles!',
 funFactTr:'Bir aslanın kükremesi 8 km uzaktan duyulabilir!',
 funFactEn:'A lion\'s roar can be heard from 8 km away!',
  },
  'hayvanlar-04': {
    emoji: '🐘',
 factTr:'Filler karada yaşayan en büyük hayvanlardır ve çok iyi hafızaları vardır!',
 factEn:'Elephants are the largest land animals and have excellent memories!',
 funFactTr:'Filler hortumlarıyla su püskürtüp duş alabilirler!',
 funFactEn:'Elephants can spray water with their trunks to take a shower!',
  },
  'hayvanlar-05': {
    emoji: '🦋',
 factTr:'Kelebekler tırtılken başlar ve sonra güzel kanatlara sahip olurlar!',
 factEn:'Butterflies start as caterpillars and then grow beautiful wings!',
 funFactTr:'Kelebekler tatları ayaklarıyla alır!',
 funFactEn:'Butterflies taste with their feet!',
  },
  'hayvanlar-06': {
    emoji: '🐰',
 factTr:'Tavşanlar çok hızlı koşabilir ve büyük kulakları sesleri çok iyi duyar!',
 factEn:'Rabbits can run very fast and their big ears hear sounds very well!',
 funFactTr:'Tavşanlar mutlu olduklarında havaya zıplayıp dönerler!',
 funFactEn:'Rabbits jump and twist in the air when they\'re happy!',
  },
  'hayvanlar-07': {
    emoji: '🐠',
 factTr:'Denizlerde 30.000\'den fazla farklı balık türü yaşar!',
 factEn:'There are over 30,000 different species of fish in the oceans!',
 funFactTr:'Bazı balıklar karanlıkta parlayabilir!',
 funFactEn:'Some fish can glow in the dark!',
  },
  'hayvanlar-08': {
    emoji: '🐦',
 factTr:'Kuşlar dinozorların torunlarıdır ve dünyada 10.000\'den fazla kuş türü vardır!',
 factEn:'Birds are descendants of dinosaurs, and there are over 10,000 bird species!',
 funFactTr:'Papağanlar insan konuşmasını taklit edebilir!',
 funFactEn:'Parrots can mimic human speech!',
  },
  'hayvanlar-09': {
    emoji: '🐴',
 factTr:'Atlar ayakta uyuyabilir ve çok güçlü hayvanlardır!',
 factEn:'Horses can sleep standing up and are very strong animals!',
 funFactTr:'Atlar neredeyse 360 derece görebilir!',
 funFactEn:'Horses can see almost 360 degrees around them!',
  },
  'hayvanlar-10': {
    emoji: '🐻',
 factTr:'Ayılar kışın uyurlar ve bu uyku bazen 5-7 ay sürebilir!',
 factEn:'Bears hibernate in winter, and this sleep can last 5-7 months!',
 funFactTr:'Ayılar köpeklerden daha iyi koklayabilir!',
 funFactEn:'Bears have a better sense of smell than dogs!',
  },
  // ===== UZAY =====
  'uzay-01': {
    emoji: '🚀',
 factTr:'Roketler uzaya çıkmak için saniyede 11 km hızla gitmek zorundadır!',
 factEn:'Rockets need to travel at 11 km per second to reach space!',
 funFactTr:'Uzaydaki ilk hayvan Laika isimli bir köpekti!',
 funFactEn:'The first animal in space was a dog named Laika!',
  },
  'uzay-02': {
    emoji: '👨‍🚀',
 factTr:'Astronotlar uzayda yüzerler çünkü orada yerçekimi çok azdır!',
 factEn:'Astronauts float in space because there is very little gravity!',
 funFactTr:'Uzayda ağlayamazsın çünkü gözyaşları yüzer!',
 funFactEn:'You can\'t cry in space because tears just float!',
  },
  'uzay-03': {
    emoji: '🪐',
 factTr:'Güneş sistemimizde 8 gezegen vardır ve Dünya üçüncüsüdür!',
 factEn:'Our solar system has 8 planets, and Earth is the third one!',
 funFactTr:'Jüpiter o kadar büyük ki içine 1.300 Dünya sığar!',
 funFactEn:'Jupiter is so big that 1,300 Earths could fit inside it!',
  },
  'uzay-04': {
    emoji: '⭐',
 factTr:'Gökyüzündeki yıldızlar aslında çok uzaktaki devasa güneşlerdir!',
 factEn:'Stars in the sky are actually giant suns that are very far away!',
 funFactTr:'Gece gökyüzünde gözle 5.000 yıldız görebilirsin!',
 funFactEn:'You can see about 5,000 stars with your eyes at night!',
  },
  'uzay-05': {
    emoji: '👽',
 factTr:'Bilim insanları uzayda başka canlılar olup olmadığını araştırıyor!',
 factEn:'Scientists are researching whether there is life elsewhere in space!',
 funFactTr:'Evrendeki yıldız sayısı dünyadaki kum tanelerinden fazla!',
 funFactEn:'There are more stars in the universe than grains of sand on Earth!',
  },
  'uzay-06': {
    emoji: '🛸',
 factTr:'Uzay gemileri güneş panelleriyle enerji üretir!',
 factEn:'Spaceships generate energy using solar panels!',
 funFactTr:'Uluslararası Uzay İstasyonu saatte 28.000 km hızla gider!',
 funFactEn:'The International Space Station travels at 28,000 km per hour!',
  },
  'uzay-07': {
    emoji: '🌙',
 factTr:'Ay, Dünya\'nın tek doğal uydusudur ve gecelerimizi aydınlatır!',
 factEn:'The Moon is Earth\'s only natural satellite and lights up our nights!',
 funFactTr:'Ay\'da yürüyen iz sonsuza kadar kalır çünkü rüzgar yok!',
 funFactEn:'Footprints on the Moon last forever because there\'s no wind!',
  },
  'uzay-08': {
    emoji: '☀️',
 factTr:'Güneş bir yıldızdır ve Dünya\'ya ışık ve sıcaklık verir!',
 factEn:'The Sun is a star that gives Earth light and warmth!',
 funFactTr:'Güneş\'in içine 1 milyon Dünya sığar!',
 funFactEn:'One million Earths could fit inside the Sun!',
  },
  'uzay-09': {
    emoji: '🪐',
 factTr:'Satürn\'ün etrafındaki halkalar buz ve kaya parçalarından oluşur!',
 factEn:'Saturn\'s rings are made of pieces of ice and rock!',
 funFactTr:'Satürn o kadar hafif ki suyun üstünde yüzebilir!',
 funFactEn:'Saturn is so light it could float on water!',
  },
  'uzay-10': {
    emoji: '🛸',
 factTr:'UFO "tanımlanamayan uçan cisim" demektir!',
 factEn:'UFO stands for "Unidentified Flying Object"!',
 funFactTr:'Her yıl binlerce kişi gökyüzünde ilginç şeyler gördüğünü söyler!',
 funFactEn:'Thousands of people report seeing strange things in the sky every year!',
  },
  // ===== DENİZ =====
  'deniz-01': {
    emoji: '🐋',
 factTr:'Mavi balina dünyanın en büyük canlısıdır ve bir otobüs kadar büyüktür!',
 factEn:'The blue whale is the largest animal on Earth, as big as a bus!',
 funFactTr:'Balina kalbi bir araba kadar büyüktür!',
 funFactEn:'A whale\'s heart is as big as a car!',
  },
  'deniz-02': {
    emoji: '🐬',
 factTr:'Yunuslar çok zeki hayvanlardır ve birbirleriyle konuşurlar!',
 factEn:'Dolphins are very smart animals and communicate with each other!',
 funFactTr:'Yunuslar uyurken bir gözleri açık kalır!',
 funFactEn:'Dolphins sleep with one eye open!',
  },
  'deniz-03': {
    emoji: '🐙',
 factTr:'Ahtapotların 8 kolu ve 3 kalbi vardır!',
 factEn:'Octopuses have 8 arms and 3 hearts!',
 funFactTr:'Ahtapotlar renk değiştirerek saklanabilir!',
 funFactEn:'Octopuses can change color to hide!',
  },
  'deniz-04': {
    emoji: '🦈',
 factTr:'Deniz atları yavaş yüzen küçük balıklardır ve babaları bebekleri taşır!',
 factEn:'Seahorses are small slow-swimming fish, and the dads carry the babies!',
 funFactTr:'Deniz atları çift olunca birbirlerinin kuyruklarını tutarlar!',
 funFactEn:'Seahorse couples hold each other\'s tails!',
  },
  'deniz-05': {
    emoji: '🐢',
 factTr:'Deniz kaplumbağaları 100 yıldan fazla yaşayabilir!',
 factEn:'Sea turtles can live for over 100 years!',
 funFactTr:'Deniz kaplumbağaları doğdukları plaja yumurta bırakmak için geri dönerler!',
 funFactEn:'Sea turtles return to the beach where they were born to lay eggs!',
  },
  'deniz-06': {
    emoji: '🦀',
 factTr:'Yengeçler yana doğru yürürler ve güçlü kıskaçları vardır!',
 factEn:'Crabs walk sideways and have strong pincers!',
 funFactTr:'Yengeçler büyüdükçe kabuklarını değiştirirler!',
 funFactEn:'Crabs change their shells as they grow!',
  },
  'deniz-07': {
    emoji: '🪼',
 factTr:'Denizanaları 500 milyon yıldır yaşıyorlar, dinozorlardan bile eskiler!',
 factEn:'Jellyfish have been around for 500 million years, even older than dinosaurs!',
 funFactTr:'Denizanalarının beyni yoktur!',
 funFactEn:'Jellyfish don\'t have brains!',
  },
  'deniz-08': {
    emoji: '🦈',
 factTr:'Köpekbalıkları aslında insanlara saldırmayı sevmez, çoğu zararsızdır!',
 factEn:'Sharks don\'t actually like attacking humans, most are harmless!',
 funFactTr:'Köpekbalıkları ömürleri boyunca 30.000 diş değiştirir!',
 funFactEn:'Sharks replace about 30,000 teeth in their lifetime!',
  },
  'deniz-09': {
    emoji: '🧜‍♀️',
 factTr:'Deniz kızları masallarda yaşar ve hayal gücümüzün en güzel kahramanlarıdır!',
 factEn:'Mermaids live in fairy tales and are among the most beautiful heroes of our imagination!',
 funFactTr:'Dünyanın birçok kültüründe deniz kızı hikayeleri vardır!',
 funFactEn:'Many cultures around the world have mermaid stories!',
  },
  'deniz-10': {
    emoji: '⭐',
 factTr:'Deniz yıldızları aslında balık değildir ve kolları kesilirse yeniden büyür!',
 factEn:'Starfish are not actually fish, and their arms grow back if cut off!',
 funFactTr:'Deniz yıldızlarının gözleri kollarının ucundadır!',
 funFactEn:'Starfish have eyes at the tips of their arms!',
  },
  // ===== MASALLAR =====
  'masallar-01': {
    emoji: '👸',
 factTr:'Prensesler masallarda cesur ve akıllı kahramanlardır!',
 factEn:'Princesses in fairy tales are brave and clever heroes!',
 funFactTr:'Dünyanın en eski masalı 4.000 yıl öncesine dayanır!',
 funFactEn:'The oldest fairy tale in the world is over 4,000 years old!',
  },
  'masallar-02': {
    emoji: '🏰',
 factTr:'Gerçek kaleler taştan yapılırdı ve içinde yüzlerce kişi yaşardı!',
 factEn:'Real castles were made of stone and hundreds of people lived inside!',
 funFactTr:'Dünyadaki en büyük kale Çek Cumhuriyeti\'ndedir!',
 funFactEn:'The largest castle in the world is in the Czech Republic!',
  },
  'masallar-03': {
    emoji: '🐉',
 factTr:'Ejderhalar masallarda yaşar ve hayal gücümüzün en harika yaratıklarıdır!',
 factEn:'Dragons live in fairy tales and are the most amazing creatures of our imagination!',
 funFactTr:'Çin\'de ejderhalar şans ve güç sembolüdür!',
 funFactEn:'In China, dragons are symbols of luck and power!',
  },
  'masallar-04': {
    emoji: '🦄',
 factTr:'Unicornlar (tek boynuzlu atlar) sihirli masallarda yaşayan güzel canlılardır!',
 factEn:'Unicorns are beautiful magical creatures that live in fairy tales!',
 funFactTr:'İskoçya\'nın ulusal hayvanı unicorndur!',
 funFactEn:'Scotland\'s national animal is the unicorn!',
  },
  'masallar-05': {
    emoji: '🧚',
 factTr:'Periler masallarda sihirli güçleri olan minik canlılardır!',
 factEn:'Fairies are tiny magical beings with special powers in fairy tales!',
 funFactTr:'İrlanda\'da hala peri kapıları yapılır ve bahçelere konulur!',
 funFactEn:'In Ireland, people still make fairy doors for their gardens!',
  },
  'masallar-06': {
    emoji: '⚔️',
 factTr:'Şövalyeler zırh giyer, at sürer ve krallarını korurdu!',
 factEn:'Knights wore armor, rode horses, and protected their kings!',
 funFactTr:'Bir şövalye zırhının ağırlığı 25 kg kadardı!',
 funFactEn:'A knight\'s armor weighed about 25 kg!',
  },
  'masallar-07': {
    emoji: '🧙',
 factTr:'Büyücüler masallarda sihirli güçleriyle harikalar yaratır!',
 factEn:'Wizards create wonders with their magical powers in fairy tales!',
 funFactTr:'Masallardaki en ünlü büyücü Merlin\'dir!',
 funFactEn:'The most famous wizard in fairy tales is Merlin!',
  },
  'masallar-08': {
    emoji: '👑',
 factTr:'Taçlar altın ve değerli taşlardan yapılır ve krallığı temsil eder!',
 factEn:'Crowns are made of gold and precious stones and represent royalty!',
 funFactTr:'İngiltere Kraliyet Tacı\'nda 2.868 elmas vardır!',
 funFactEn:'The British Crown has 2,868 diamonds!',
  },
  'masallar-09': {
    emoji: '🪄',
 factTr:'Sihirli lamba masalında Alaaddin\'in cin çağıran lambası vardır!',
 factEn:'In the fairy tale, Aladdin has a magical lamp that summons a genie!',
 funFactTr:'1001 Gece Masalları 1.000 yıldan eski hikayeler içerir!',
 funFactEn:'The 1001 Nights tales contain stories over 1,000 years old!',
  },
  'masallar-10': {
    emoji: '🏴‍☠️',
 factTr:'Korsanlar denizlerde macera yaşayan cesur denizcilerdir!',
 factEn:'Pirates were brave sailors who had adventures on the seas!',
 funFactTr:'Korsanlar göz bandını karanlığa alışmak için takardı!',
 funFactEn:'Pirates wore eye patches to adjust to darkness below deck!',
  },
  // ===== ARAÇLAR =====
  'araclar-01': {
    emoji: '🚗',
 factTr:'İlk otomobil 1886 yılında Almanya\'da Karl Benz tarafından yapıldı!',
 factEn:'The first car was made in 1886 in Germany by Karl Benz!',
 funFactTr:'Dünyadaki arabaların ortalama ömrü 12 yıldır!',
 funFactEn:'The average lifespan of a car is 12 years!',
  },
  'araclar-02': {
    emoji: '🚛',
 factTr:'Kamyonlar ağır yükleri uzun mesafelere taşırlar!',
 factEn:'Trucks carry heavy loads over long distances!',
 funFactTr:'Dünyanın en büyük kamyonu bir ev kadar büyüktür!',
 funFactEn:'The biggest truck in the world is as big as a house!',
  },
  'araclar-03': {
    emoji: '✈️',
 factTr:'Uçaklar gökyüzünde kuşlardan bile yüksekte uçar!',
 factEn:'Airplanes fly higher in the sky than even birds!',
 funFactTr:'Wright Kardeşler ilk uçuşu 1903\'te gerçekleştirdi!',
 funFactEn:'The Wright Brothers made the first flight in 1903!',
  },
  'araclar-04': {
    emoji: '🚂',
 factTr:'Trenler raylarda gider ve bir seferde yüzlerce yolcu taşıyabilir!',
 factEn:'Trains run on rails and can carry hundreds of passengers at once!',
 funFactTr:'Japonya\'daki hızlı tren saatte 320 km hıza ulaşır!',
 funFactEn:'Japan\'s bullet train reaches speeds of 320 km per hour!',
  },
  'araclar-05': {
    emoji: '🚁',
 factTr:'Helikopterler havada sabit durabilir ve dikey olarak inip kalkabilir!',
 factEn:'Helicopters can hover in the air and take off vertically!',
 funFactTr:'Leonardo da Vinci 500 yıl önce helikopter çizimi yapmıştı!',
 funFactEn:'Leonardo da Vinci drew a helicopter design 500 years ago!',
  },
  'araclar-06': {
    emoji: '🚢',
 factTr:'Büyük gemiler okyanusları geçebilir ve binlerce konteyner taşıyabilir!',
 factEn:'Big ships can cross oceans and carry thousands of containers!',
 funFactTr:'Dünyanın en büyük gemisi 4 futbol sahası uzunluğundadır!',
 funFactEn:'The biggest ship is as long as 4 football fields!',
  },
  'araclar-07': {
    emoji: '🚲',
 factTr:'Bisiklet çevre dostu bir ulaşım aracıdır ve egzersiz yapmamızı sağlar!',
 factEn:'Bicycles are eco-friendly transportation and help us exercise!',
 funFactTr:'Dünyada 1 milyardan fazla bisiklet vardır!',
 funFactEn:'There are over 1 billion bicycles in the world!',
  },
  'araclar-08': {
    emoji: '🚌',
 factTr:'Otobüsler şehirlerde insanları bir yerden başka yere taşır!',
 factEn:'Buses transport people from one place to another in cities!',
 funFactTr:'Londra\'nın kırmızı iki katlı otobüsleri çok ünlüdür!',
 funFactEn:'London\'s red double-decker buses are world famous!',
  },
  'araclar-09': {
    emoji: '🏍️',
 factTr:'Motosikletler iki tekerlek üzerinde giden hızlı araçlardır!',
 factEn:'Motorcycles are fast vehicles that ride on two wheels!',
 funFactTr:'İlk motosiklet 1885 yılında yapıldı!',
 funFactEn:'The first motorcycle was made in 1885!',
  },
  'araclar-10': {
    emoji: '🚒',
 factTr:'İtfaiye araçları yangınlara çok hızlı ulaşır ve insanları kurtarır!',
 factEn:'Fire trucks reach fires very quickly and rescue people!',
 funFactTr:'İtfaiyeciler yangın söndürme eğitiminde gerçek ateşle çalışır!',
 funFactEn:'Firefighters train with real fire to learn how to put out fires!',
  },
  // ===== DOĞA =====
  'doga-01': {
    emoji: '🌸',
 factTr:'Dünyada 400.000\'den fazla çiçek türü vardır ve kelebekler çiçekleri sever!',
 factEn:'There are over 400,000 flower species in the world and butterflies love flowers!',
 funFactTr:'Ayçiçekleri her zaman güneşe doğru döner!',
 funFactEn:'Sunflowers always turn toward the sun!',
  },
  'doga-02': {
    emoji: '🌳',
 factTr:'Ağaçlar bize nefes almamız için oksijen verir ve havayı temizler!',
 factEn:'Trees give us oxygen to breathe and clean the air!',
 funFactTr:'Dünyanın en yaşlı ağacı 5.000 yıldan fazladır!',
 funFactEn:'The oldest tree in the world is over 5,000 years old!',
  },
  'doga-03': {
    emoji: '🌈',
 factTr:'Gökkuşağı güneş ışığının yağmur damlalarından geçmesiyle oluşur!',
 factEn:'Rainbows form when sunlight passes through raindrops!',
 funFactTr:'Gökkuşağında 7 renk vardır: kırmızı, turuncu, sarı, yeşil, mavi, çivit, mor!',
 funFactEn:'A rainbow has 7 colors: red, orange, yellow, green, blue, indigo, violet!',
  },
  'doga-04': {
    emoji: '⛰️',
 factTr:'Everest Dağı dünyanın en yüksek noktasıdır, 8.849 metre yüksekliğindedir!',
 factEn:'Mount Everest is the highest point on Earth at 8,849 meters!',
 funFactTr:'Dağların tepesinde kar hiç erimez!',
 funFactEn:'Snow on top of mountains never melts!',
  },
  'doga-05': {
    emoji: '💧',
 factTr:'Şelaleler nehirlerin uçurumdan aşağı düşmesiyle oluşur ve çok güzeldir!',
 factEn:'Waterfalls form when rivers fall off cliffs and they are very beautiful!',
 funFactTr:'Dünyanın en yüksek şelalesi 979 metredir!',
 funFactEn:'The tallest waterfall in the world is 979 meters!',
  },
  'doga-06': {
    emoji: '🍄',
 factTr:'Mantarlar ne bitki ne de hayvan, ayrı bir canlı grubundadır!',
 factEn:'Mushrooms are neither plants nor animals, they are a separate group!',
 funFactTr:'Dünyanın en büyük canlısı bir mantar ağıdır!',
 funFactEn:'The largest living thing in the world is a mushroom network!',
  },
  'doga-07': {
    emoji: '🍂',
 factTr:'Sonbaharda yapraklar yeşilden sarıya ve kırmızıya döner!',
 factEn:'In autumn, leaves change from green to yellow and red!',
 funFactTr:'Yapraklar renklerini klorofil azaldığı için değiştirir!',
 funFactEn:'Leaves change color because chlorophyll decreases!',
  },
  'doga-08': {
    emoji: '🌹',
 factTr:'Güller en popüler çiçeklerden biridir ve 30.000\'den fazla çeşidi vardır!',
 factEn:'Roses are one of the most popular flowers with over 30,000 varieties!',
 funFactTr:'En eski gül fosili 35 milyon yıl öncesine aittir!',
 funFactEn:'The oldest rose fossil is 35 million years old!',
  },
  'doga-09': {
    emoji: '🌻',
 factTr:'Ayçiçekleri güneşi takip eder ve çekirdekleri çok lezzetlidir!',
 factEn:'Sunflowers follow the sun and their seeds are very tasty!',
 funFactTr:'Bir ayçiçeğinde 2.000\'e kadar çekirdek olabilir!',
 funFactEn:'A sunflower can have up to 2,000 seeds!',
  },
  'doga-10': {
    emoji: '🌲',
 factTr:'Ormanlar dünyamızın ciğerleridir ve birçok hayvan ormanda yaşar!',
 factEn:'Forests are the lungs of our planet and many animals live in forests!',
 funFactTr:'Amazon Ormanı dünya oksijeninin %20\'sini üretir!',
 funFactEn:'The Amazon Forest produces 20% of the world\'s oxygen!',
  },
  // ===== DİNOZORLAR =====
  'dinozorlar-01': {
    emoji: '🦖',
 factTr:'T-Rex en güçlü yırtıcı dinozorlardan biriydi ve 12 metre uzunluğundaydı!',
 factEn:'T-Rex was one of the strongest predator dinosaurs and was 12 meters long!',
 funFactTr:'T-Rex\'in kolları çok kısa ama ısırığı çok güçlüydü!',
 funFactEn:'T-Rex had very short arms but an incredibly powerful bite!',
  },
  'dinozorlar-02': {
    emoji: '🦕',
 factTr:'Triceratops üç boynuzlu bir dinozordur ve otçuldu!',
 factEn:'Triceratops had three horns and was a herbivore!',
 funFactTr:'Triceratops\'un kafası bir araba kadar büyüktü!',
 funFactEn:'Triceratops\' head was as big as a car!',
  },
  'dinozorlar-03': {
    emoji: '🦕',
 factTr:'Stegosaurus sırtındaki plakalarıyla tanınır ve otçul bir dinozordu!',
 factEn:'Stegosaurus is known for the plates on its back and was a herbivore!',
 funFactTr:'Stegosaurus\'un beyni bir ceviz kadar küçüktü!',
 funFactEn:'Stegosaurus had a brain the size of a walnut!',
  },
  'dinozorlar-04': {
    emoji: '🦅',
 factTr:'Pterodactyl uçabilen bir sürüngendi ama aslında dinozor değildi!',
 factEn:'Pterodactyl was a flying reptile but was not actually a dinosaur!',
 funFactTr:'Kanat açıklığı 10 metreden fazla olabilirdi!',
 funFactEn:'Its wingspan could be over 10 meters!',
  },
  'dinozorlar-05': {
    emoji: '🦕',
 factTr:'Brontosaurus çok uzun boyunlu bir dinozordu ve yaprak yerdi!',
 factEn:'Brontosaurus had a very long neck and ate leaves!',
 funFactTr:'Brontosaurus 22 metre uzunluğundaydı, 4 otobüs kadar!',
 funFactEn:'Brontosaurus was 22 meters long, like 4 buses!',
  },
  'dinozorlar-06': {
    emoji: '🦖',
 factTr:'Velociraptor küçük ama çok hızlı bir yırtıcıydı!',
 factEn:'Velociraptor was small but a very fast predator!',
 funFactTr:'Velociraptor aslında tüylüydü, filmlerdeki gibi değildi!',
 funFactEn:'Velociraptor actually had feathers, unlike in movies!',
  },
  'dinozorlar-07': {
    emoji: '🥚',
 factTr:'Dinozorlar yumurtadan doğardı, tıpkı kuşlar ve kaplumbağalar gibi!',
 factEn:'Dinosaurs hatched from eggs, just like birds and turtles!',
 funFactTr:'Bulunan en büyük dinozor yumurtası 30 cm uzunluğundaydı!',
 funFactEn:'The largest dinosaur egg found was 30 cm long!',
  },
  'dinozorlar-08': {
    emoji: '🌋',
 factTr:'Yanardağlar yeraltındaki sıcak kayanın yeryüzüne çıkmasıyla oluşur!',
 factEn:'Volcanoes form when hot underground rock rises to the surface!',
 funFactTr:'Dünyada 1.500\'den fazla aktif yanardağ vardır!',
 funFactEn:'There are over 1,500 active volcanoes on Earth!',
  },
  'dinozorlar-09': {
    emoji: '🦕',
 factTr:'Yavru dinozorlar anne babalarının bakımıyla büyürdü!',
 factEn:'Baby dinosaurs grew up with the care of their parents!',
 funFactTr:'Bazı yavru dinozorlar doğduklarında bir kedi kadardı!',
 funFactEn:'Some baby dinosaurs were as small as a cat when born!',
  },
  'dinozorlar-10': {
    emoji: '🦕',
 factTr:'Dinozorlar 165 milyon yıl boyunca dünyada yaşadı!',
 factEn:'Dinosaurs lived on Earth for 165 million years!',
 funFactTr:'İnsanlar sadece 300.000 yıldır varız, dinozorlar çok daha uzun yaşadı! ⏰',
 funFactEn:'Humans have been here only 300,000 years, dinosaurs lived much longer! ⏰',
  },
  // ===== YİYECEKLER =====
  'yiyecekler-01': {
    emoji: '🎂',
 factTr:'Doğum günü pastası geleneği eski Yunan\'da başladı!',
 factEn:'The birthday cake tradition started in ancient Greece!',
 funFactTr:'Dünyanın en büyük pastası 58 metre uzunluğundaydı!',
 funFactEn:'The world\'s largest cake was 58 meters long!',
  },
  'yiyecekler-02': {
    emoji: '🍦',
 factTr:'Dondurma yaklaşık 2.000 yıl önce Çin\'de icat edildi!',
 factEn:'Ice cream was invented in China about 2,000 years ago!',
 funFactTr:'En popüler dondurma aroması vanilyaadır!',
 funFactEn:'The most popular ice cream flavor is vanilla!',
  },
  'yiyecekler-03': {
    emoji: '🍕',
 factTr:'Pizza İtalya\'dan gelir ve dünyada en sevilen yiyeceklerden biridir!',
 factEn:'Pizza comes from Italy and is one of the most loved foods in the world!',
 funFactTr:'Dünyada her saniye 350 dilim pizza yenir!',
 funFactEn:'350 slices of pizza are eaten every second worldwide!',
  },
  'yiyecekler-04': {
    emoji: '🍎',
 factTr:'Meyveler vücudumuz için çok faydalıdır ve bizi güçlü yapar!',
 factEn:'Fruits are very good for our body and make us strong!',
 funFactTr:'Çilekler aslında meyve değil, aksesuar meyvedir!',
 funFactEn:'Strawberries aren\'t actually berries!',
  },
  'yiyecekler-05': {
    emoji: '🧁',
 factTr:'Cupcake\'ler küçük porsiyonluk pastacıklardır ve süslenmesi çok eğlencelidir!',
 factEn:'Cupcakes are small portion cakes and decorating them is very fun!',
 funFactTr:'İlk cupcake tarifi 1796 yılına aittir!',
 funFactEn:'The first cupcake recipe dates back to 1796!',
  },
  'yiyecekler-06': {
    emoji: '🍪',
 factTr:'Kurabiye Farsça "küçük kek" anlamına gelir!',
 factEn:'Cookie comes from the Dutch word "koekje" meaning "little cake"!',
 funFactTr:'Çikolatalı kurabiye aslında yanlışlıkla icat edildi!',
 funFactEn:'Chocolate chip cookies were invented by accident!',
  },
  'yiyecekler-07': {
    emoji: '🍩',
 factTr:'Donut ortasındaki delik hamuru eşit pişirmek için yapılır!',
 factEn:'The hole in a donut is made so the dough cooks evenly!',
 funFactTr:'Amerika\'da her yıl 10 milyar donut yenir!',
 funFactEn:'Americans eat 10 billion donuts every year!',
  },
  'yiyecekler-08': {
    emoji: '🍬',
 factTr:'Şekerler eski zamanlarda bal ve meyvelerden yapılırdı!',
 factEn:'In ancient times, candies were made from honey and fruits!',
 funFactTr:'Pamuk şeker aslında bir diş doktoru tarafından icat edildi!',
 funFactEn:'Cotton candy was actually invented by a dentist!',
  },
  'yiyecekler-09': {
    emoji: '🍔',
 factTr:'Hamburger adını Almanya\'daki Hamburg şehrinden alır!',
 factEn:'The hamburger gets its name from the city of Hamburg in Germany!',
 funFactTr:'Dünyanın en pahalı hamburgeri 5.000 dolar!',
 funFactEn:'The most expensive hamburger in the world costs $5,000!',
  },
  'yiyecekler-10': {
    emoji: '🍉',
 factTr:'Karpuz %92 sudan oluşur ve yaz aylarında çok serinleticidir!',
 factEn:'Watermelon is 92% water and is very refreshing in summer!',
 funFactTr:'Dünyanın en ağır karpuzu 159 kg geldi!',
 funFactEn:'The heaviest watermelon in the world weighed 159 kg!',
  },
  // ===== ŞEHİR =====
  'sehir-01': {
    emoji: '🏠',
 factTr:'Evler bizi sıcak tutar, yağmurdan korur ve güvende hissettirir!',
 factEn:'Houses keep us warm, protect us from rain, and make us feel safe!',
 funFactTr:'Dünyadaki en küçük ev sadece 1 metrekare!',
 funFactEn:'The smallest house in the world is only 1 square meter!',
  },
  'sehir-02': {
    emoji: '🏢',
 factTr:'Gökdelenler çok yüksek binalardır ve yüzlerce kat olabilir!',
 factEn:'Skyscrapers are very tall buildings and can have hundreds of floors!',
 funFactTr:'Dünyanın en yüksek binası 828 metredir!',
 funFactEn:'The tallest building in the world is 828 meters!',
  },
  'sehir-03': {
    emoji: '🏫',
 factTr:'Okullar öğrenmenin ve arkadaşlıkların kurulduğu harika yerlerdir!',
 factEn:'Schools are wonderful places where we learn and make friends!',
 funFactTr:'Dünyanın en eski okulu 1.000 yıldan fazladır!',
 funFactEn:'The oldest school in the world is over 1,000 years old!',
  },
  'sehir-04': {
    emoji: '🎢',
 factTr:'Oyun parkları eğlence, spor ve arkadaşlarla vakit geçirmek içindir!',
 factEn:'Playgrounds are for fun, exercise, and spending time with friends!',
 funFactTr:'Salıncak 5.000 yıldan fazladır çocukların favorisi!',
 funFactEn:'Swings have been children\'s favorite for over 5,000 years!',
  },
  'sehir-05': {
    emoji: '🌳',
 factTr:'Parklar şehirlerde doğayla buluştuğumuz yeşil alanlardır!',
 factEn:'Parks are green spaces in cities where we connect with nature!',
 funFactTr:'New York\'taki Central Park\'ta 25.000\'den fazla ağaç vardır!',
 funFactEn:'Central Park in New York has over 25,000 trees!',
  },
  'sehir-06': {
    emoji: '🌉',
 factTr:'Köprüler nehirlerin ve vadilerin üstünden geçmemizi sağlar!',
 factEn:'Bridges help us cross over rivers and valleys!',
 funFactTr:'Dünyanın en uzun köprüsü 164 km\'dir!',
 funFactEn:'The longest bridge in the world is 164 km!',
  },
  'sehir-07': {
    emoji: '🏮',
 factTr:'Deniz fenerleri gemilere yol gösterir ve onları kayalıklardan korur!',
 factEn:'Lighthouses guide ships and protect them from rocks!',
 funFactTr:'En eski deniz feneri 2.300 yıl öncesine aittir!',
 funFactEn:'The oldest lighthouse dates back 2,300 years!',
  },
  'sehir-08': {
    emoji: '🌾',
 factTr:'Yel değirmenleri rüzgarın gücünü kullanarak tahıl öğütür!',
 factEn:'Windmills use wind power to grind grain!',
 funFactTr:'Hollanda dünyaca ünlü yel değirmenleriyle tanınır!',
 funFactEn:'The Netherlands is famous for its windmills!',
  },
  'sehir-09': {
    emoji: '🐄',
 factTr:'Çiftlikler yiyeceklerimizin yetiştirildiği ve hayvanların bakıldığı yerlerdir!',
 factEn:'Farms are where our food is grown and animals are cared for!',
 funFactTr:'Bir inek günde 200 litre süt verebilir!',
 funFactEn:'A cow can produce 200 liters of milk per day!',
  },
  'sehir-10': {
    emoji: '🚉',
 factTr:'Tren istasyonları insanların trenlere binip indiği yerlerdir!',
 factEn:'Train stations are where people board and exit trains!',
 funFactTr:'Dünyanın en işlek istasyonu Tokyo\'daki Shinjuku\'dur!',
 funFactEn:'The busiest station in the world is Shinjuku in Tokyo!',
  },
  // ===== TATİL =====
  'tatil-01': {
    emoji: '🎄',
 factTr:'Noel ağacı süsleme geleneği 500 yıl öncesine dayanır!',
 factEn:'The tradition of decorating Christmas trees dates back 500 years!',
 funFactTr:'Her yıl dünyada 35 milyon Noel ağacı satılır!',
 funFactEn:'35 million Christmas trees are sold worldwide every year!',
  },
  'tatil-02': {
    emoji: '🎃',
 factTr:'Cadılar Bayramı\'nda çocuklar kostüm giyer ve şeker toplar!',
 factEn:'On Halloween, children wear costumes and collect candy!',
 funFactTr:'En ağır balkabağı 1.190 kg geldi!',
 funFactEn:'The heaviest pumpkin weighed 1,190 kg!',
  },
  'tatil-03': {
    emoji: '🐣',
 factTr:'Paskalya baharın gelişini kutlayan renkli bir bayramdır!',
 factEn:'Easter is a colorful holiday celebrating the arrival of spring!',
 funFactTr:'Dünyanın en büyük Paskalya yumurtası 10 metre yüksekliğindeydi!',
 funFactEn:'The largest Easter egg was 10 meters tall!',
  },
  'tatil-04': {
    emoji: '🎂',
 factTr:'Doğum günleri her yıl bir yaş büyüdüğümüzü kutladığımız özel günlerdir!',
 factEn:'Birthdays are special days when we celebrate growing one year older!',
 funFactTr:'En çok doğum günü Eylül ayında kutlanır!',
 funFactEn:'September has the most birthdays of any month!',
  },
  'tatil-05': {
    emoji: '⛄',
 factTr:'Kardan adam yapmak kış mevsiminin en eğlenceli aktivitesidir!',
 factEn:'Building a snowman is the most fun activity of winter!',
 funFactTr:'Dünyanın en büyük kardan adamı 37 metre yüksekliğindeydi!',
 funFactEn:'The tallest snowman ever was 37 meters tall!',
  },
  'tatil-06': {
    emoji: '🎅',
 factTr:'Noel Baba çocuklara hediye getiren neşeli ve sevilen bir karakterdir!',
 factEn:'Santa Claus is a cheerful and beloved character who brings gifts to children!',
 funFactTr:'Noel Baba\'nın ren geyiklerinin hepsinin isimleri vardır!',
 funFactEn:'All of Santa\'s reindeer have names!',
  },
  'tatil-07': {
    emoji: '🎃',
 factTr:'Balkabağı hem yiyecek hem de dekorasyon olarak kullanılır!',
 factEn:'Pumpkins are used both as food and as decorations!',
 funFactTr:'Balkabağı aslında bir meyvedir, sebze değil!',
 funFactEn:'Pumpkins are actually fruits, not vegetables!',
  },
  'tatil-08': {
    emoji: '❤️',
 factTr:'Sevgililer Günü\'nde insanlar sevdiklerine kart ve çiçek verir!',
 factEn:'On Valentine\'s Day, people give cards and flowers to their loved ones!',
 funFactTr:'Her yıl 1 milyardan fazla Sevgililer Günü kartı gönderilir!',
 funFactEn:'Over 1 billion Valentine\'s Day cards are sent every year!',
  },
  'tatil-09': {
    emoji: '🎆',
 factTr:'Havai fişekler kutlamalarda gökyüzünü rengarenk yapar!',
 factEn:'Fireworks make the sky colorful during celebrations!',
 funFactTr:'Havai fişek 2.000 yıl önce Çin\'de icat edildi!',
 funFactEn:'Fireworks were invented in China 2,000 years ago!',
  },
  'tatil-10': {
    emoji: '🎁',
 factTr:'Hediye vermek sevgi göstermenin en güzel yollarından biridir!',
 factEn:'Giving gifts is one of the most beautiful ways to show love!',
 funFactTr:'Hediye ambalaj kağıdı 1917 yılında icat edildi!',
 funFactEn:'Gift wrapping paper was invented in 1917!',
  },
};
