export const INSPIRATIONS: Record<string, string[]> = {
  tr: [
    'Bir fil balerin olsa nasıl olurdu? 🐘💃',
    'Ya bulutlar pamuk şekere dönüşse? ☁️🍭',
    'Uzayda bir kedi kafesi olsa? 🐱🚀',
    'Denizaltında bir lunapark hayal et! 🎡🐠',
    'Gökkuşağının üstünde kayan bir penguen! 🐧🌈',
    'Bir ejderha dondurma satsa? 🐉🍦',
    'Aya giden bir bisiklet yolu! 🚲🌙',
    'Robot bir aşçı pasta yapıyor! 🤖🎂',
    'Çiçeklerden yapılmış bir uzay gemisi! 🌸🚀',
    'Kanatları olan bir kaplumbağa! 🐢✨',
    'Büyülü bir ormanın kapısı! 🚪🌳',
    'Bir balık okula gitse? 🐟📚',
    'Müzik çalan bir ağaç! 🎵🌲',
    'Çizmeleri olan bir ahtapot! 🐙👢',
    'Balonlarla uçan bir ev! 🎈🏠',
    'Patenleri olan bir zürafa! 🦒⛸️',
    'Bir kelebek sirki! 🦋🎪',
    'Bulutlarda yüzen bir gemi! ⛵☁️',
    'Rengarenk bir unicorn ailesi! 🦄🌈',
    'Dansçı bir dinozor! 🦕💃',
  ],
  en: [
    'What if an elephant was a ballerina? 🐘💃',
    'What if clouds turned into cotton candy? ☁️🍭',
    'A cat cafe in outer space? 🐱🚀',
    'Imagine an underwater amusement park! 🎡🐠',
    'A penguin sliding on a rainbow! 🐧🌈',
    'A dragon selling ice cream? 🐉🍦',
    'A bicycle path to the moon! 🚲🌙',
    'A robot chef baking a cake! 🤖🎂',
    'A spaceship made of flowers! 🌸🚀',
    'A turtle with wings! 🐢✨',
    'A magical door in the forest! 🚪🌳',
    'What if a fish went to school? 🐟📚',
    'A tree that plays music! 🎵🌲',
    'An octopus wearing boots! 🐙👢',
    'A house flying with balloons! 🎈🏠',
    'A giraffe on roller skates! 🦒⛸️',
    'A butterfly circus! 🦋🎪',
    'A ship floating in the clouds! ⛵☁️',
    'A colorful unicorn family! 🦄🌈',
    'A dancing dinosaur! 🦕💃',
  ],
};

export function getRandomInspiration(locale: string = 'tr'): string {
  const list = INSPIRATIONS[locale] || INSPIRATIONS.tr;
  return list[Math.floor(Math.random() * list.length)];
}

export const PROMPT_SUGGESTIONS: Record<string, { emoji: string; text: string }[]> = {
  tr: [
    { emoji: '🦄', text: 'Gökkuşağında koşan bir unicorn' },
    { emoji: '🐉', text: 'Ateş püskürten sevimli ejderha' },
    { emoji: '🧚', text: 'Çiçek bahçesinde peri kızı' },
    { emoji: '🐳', text: 'Okyanusta yüzen mutlu balina' },
    { emoji: '👨‍🚀', text: 'Ayda yürüyen astronot' },
    { emoji: '🏴‍☠️', text: 'Hazine arayan korsan gemisi' },
    { emoji: '🦁', text: 'Ormanda oynayan bir aslan' },
    { emoji: '🐱', text: 'Uzayda yüzen bir kedi' },
    { emoji: '🦕', text: 'Paten kayan bir dinozor' },
    { emoji: '🐙', text: 'Şapka takan bir ahtapot' },
    { emoji: '🏰', text: 'Bulutların üstünde bir kale' },
    { emoji: '🍕', text: 'Kanatları olan bir pizza' },
    { emoji: '🐘', text: 'Balonlarla uçan bir fil' },
    { emoji: '🦋', text: 'Gökkuşağı kanatlı kelebek' },
    { emoji: '🐧', text: 'Sörf yapan bir penguen' },
    { emoji: '🦊', text: 'Kitap okuyan bir tilki' },
    { emoji: '🐸', text: 'Taç takan bir kurbağa prens' },
    { emoji: '🦒', text: 'Bisiklet süren bir zürafa' },
    { emoji: '🐻', text: 'Bal yiyen sevimli bir ayı' },
    { emoji: '🦜', text: 'Korsan papağanı ve hazine sandığı' },
    { emoji: '🌋', text: 'Yanardağdan çiçek fışkırıyor' },
    { emoji: '🧜‍♀️', text: 'Deniz altında bir deniz kızı' },
    { emoji: '🤖', text: 'Çiçek sulayan sevimli robot' },
    { emoji: '🐰', text: 'Havuç bahçesinde bir tavşan' },
    { emoji: '🦈', text: 'Gülümseyen bir köpekbalığı' },
    { emoji: '🎪', text: 'Sirkte gösteri yapan bir fil' },
    { emoji: '🐢', text: 'Yarış kazanan bir kaplumbağa' },
    { emoji: '🦩', text: 'Göl kenarında dans eden flamingo' },
    { emoji: '🐨', text: 'Ağaçta uyuyan bir koala' },
    { emoji: '🦝', text: 'Pasta yapan bir rakun' },
    { emoji: '🐬', text: 'Dalgalarla oynayan yunuslar' },
    { emoji: '🦅', text: 'Dağların üstünde süzülen kartal' },
    { emoji: '🐝', text: 'Çiçekler arasında uçan arı' },
    { emoji: '🎠', text: 'Lunaparkta atlıkarınca' },
    { emoji: '🚂', text: 'Gökkuşağı treni' },
    { emoji: '🏖️', text: 'Plajda kum kalesi yapan yengeç' },
    { emoji: '🌺', text: 'Dev bir çiçeğin üstünde oturan böcek' },
    { emoji: '🧁', text: 'Cupcake evde yaşayan fare' },
    { emoji: '🐴', text: 'Çayırda koşan vahşi atlar' },
    { emoji: '🦔', text: 'Yapraklar arasında sevimli kirpi' },
  ],
  en: [
    { emoji: '🦄', text: 'A unicorn running on a rainbow' },
    { emoji: '🐉', text: 'A cute fire-breathing dragon' },
    { emoji: '🧚', text: 'A fairy in a flower garden' },
    { emoji: '🐳', text: 'A happy whale swimming in the ocean' },
    { emoji: '👨‍🚀', text: 'An astronaut walking on the moon' },
    { emoji: '🏴‍☠️', text: 'A pirate ship hunting treasure' },
    { emoji: '🦁', text: 'A lion playing in the forest' },
    { emoji: '🐱', text: 'A cat floating in space' },
    { emoji: '🦕', text: 'A dinosaur roller skating' },
    { emoji: '🐙', text: 'An octopus wearing a hat' },
    { emoji: '🏰', text: 'A castle above the clouds' },
    { emoji: '🍕', text: 'A pizza with wings' },
    { emoji: '🐘', text: 'An elephant flying with balloons' },
    { emoji: '🦋', text: 'A rainbow-winged butterfly' },
    { emoji: '🐧', text: 'A penguin surfing' },
    { emoji: '🦊', text: 'A fox reading a book' },
    { emoji: '🐸', text: 'A frog prince with a crown' },
    { emoji: '🦒', text: 'A giraffe riding a bicycle' },
    { emoji: '🐻', text: 'A cute bear eating honey' },
    { emoji: '🦜', text: 'A pirate parrot and treasure chest' },
    { emoji: '🌋', text: 'Flowers bursting from a volcano' },
    { emoji: '🧜‍♀️', text: 'A mermaid under the sea' },
    { emoji: '🤖', text: 'A cute robot watering flowers' },
    { emoji: '🐰', text: 'A bunny in a carrot garden' },
    { emoji: '🦈', text: 'A smiling shark' },
    { emoji: '🎪', text: 'An elephant performing in a circus' },
    { emoji: '🐢', text: 'A turtle winning a race' },
    { emoji: '🦩', text: 'A flamingo dancing by a lake' },
    { emoji: '🐨', text: 'A koala sleeping in a tree' },
    { emoji: '🦝', text: 'A raccoon baking a cake' },
    { emoji: '🐬', text: 'Dolphins playing with waves' },
    { emoji: '🦅', text: 'An eagle soaring over mountains' },
    { emoji: '🐝', text: 'A bee flying among flowers' },
    { emoji: '🎠', text: 'A merry-go-round at the carnival' },
    { emoji: '🚂', text: 'A rainbow train' },
    { emoji: '🏖️', text: 'A crab building a sandcastle' },
    { emoji: '🌺', text: 'A bug sitting on a giant flower' },
    { emoji: '🧁', text: 'A mouse living in a cupcake house' },
    { emoji: '🐴', text: 'Wild horses running in a meadow' },
    { emoji: '🦔', text: 'A cute hedgehog among leaves' },
  ],
};

export function getRandomSuggestions(count: number = 6, locale: string = 'tr') {
  const list = PROMPT_SUGGESTIONS[locale] || PROMPT_SUGGESTIONS.tr;
  const shuffled = [...list].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
