// Auto-generated by scripts/generate-stock.js
// Do not edit manually

export interface StockImage {
  id: string;
  filename: string;
  path: string;
  category: string;
  title: string;
}

export interface StockCategory {
  id: string;
  name: string;
  emoji: string;
  images: StockImage[];
}

// English translations for category names
export const CATEGORY_NAMES_EN: Record<string, string> = {
  hayvanlar: 'Animals',
  uzay: 'Space',
  deniz: 'Sea & Ocean',
  masallar: 'Fairy Tales & Fantasy',
  araclar: 'Vehicles',
  doga: 'Nature & Flowers',
  dinozorlar: 'Dinosaurs',
  yiyecekler: 'Food',
  sehir: 'Home & City',
  tatil: 'Holidays',
  alfabe: 'Alphabet',
  sayilar: 'Numbers',
  gezegenler: 'Planets',
  alphabet: 'Alphabet',
};

// English translations for image titles
export const IMAGE_TITLES_EN: Record<string, string> = {
  'Sevimli Kedi': 'Cute Cat', 'Neşeli Köpek': 'Happy Puppy', 'Cesur Aslan': 'Brave Lion',
  'Kocaman Fil': 'Big Elephant', 'Güzel Kelebek': 'Beautiful Butterfly', 'Şirin Tavşan': 'Cute Bunny',
  'Renkli Balık': 'Colorful Fish', 'Ötücü Kuş': 'Singing Bird', 'Zarif At': 'Graceful Horse', 'Tatlı Ayı': 'Sweet Bear',
  'Roket': 'Rocket', 'Astronot': 'Astronaut', 'Gezegen': 'Planet', 'Yıldızlar': 'Stars',
  'Uzaylı': 'Alien', 'Uzay Gemisi': 'Spaceship', 'Ay': 'Moon', 'Güneş': 'Sun', 'Satürn': 'Saturn', 'UFO': 'UFO',
  'Balina': 'Whale', 'Yunus': 'Dolphin', 'Ahtapot': 'Octopus', 'Deniz Atı': 'Seahorse',
  'Kaplumbağa': 'Turtle', 'Yengeç': 'Crab', 'Denizanası': 'Jellyfish', 'Köpekbalığı': 'Shark',
  'Deniz Kızı': 'Mermaid', 'Deniz Yıldızı': 'Starfish',
  'Prenses': 'Princess', 'Kale': 'Castle', 'Ejderha': 'Dragon', 'Unicorn': 'Unicorn',
  'Peri': 'Fairy', 'Şövalye': 'Knight', 'Büyücü': 'Wizard', 'Taç': 'Crown',
  'Sihirli Lamba': 'Magic Lamp', 'Korsan': 'Pirate',
  'Araba': 'Car', 'Kamyon': 'Truck', 'Uçak': 'Airplane', 'Tren': 'Train',
  'Helikopter': 'Helicopter', 'Gemi': 'Ship', 'Bisiklet': 'Bicycle', 'Otobüs': 'School Bus',
  'Motosiklet': 'Motorcycle', 'İtfaiye': 'Fire Truck',
  'Çiçek Bahçesi': 'Flower Garden', 'Büyük Ağaç': 'Big Tree', 'Gökkuşağı': 'Rainbow',
  'Dağ Manzarası': 'Mountain Landscape', 'Şelale': 'Waterfall', 'Mantar': 'Mushroom',
  'Yaprak': 'Leaf', 'Gül': 'Rose', 'Ayçiçeği': 'Sunflower', 'Orman': 'Forest',
  'T-Rex': 'T-Rex', 'Triceratops': 'Triceratops', 'Stegosaurus': 'Stegosaurus',
  'Pterodactyl': 'Pterodactyl', 'Brontosaurus': 'Brontosaurus', 'Raptor': 'Raptor',
  'Dinozor Yumurtası': 'Dinosaur Egg', 'Yanardağ': 'Volcano', 'Bebek Dino': 'Baby Dino', 'Dino Ailesi': 'Dino Family',
  'Pasta': 'Cake', 'Dondurma': 'Ice Cream', 'Pizza': 'Pizza', 'Meyveler': 'Fruits',
  'Cupcake': 'Cupcake', 'Kurabiye': 'Cookie', 'Donut': 'Donut', 'Şeker': 'Candy',
  'Hamburger': 'Hamburger', 'Karpuz': 'Watermelon',
  'Ev': 'House', 'Binalar': 'Buildings', 'Okul': 'School', 'Oyun Parkı': 'Playground',
  'Park': 'Park', 'Köprü': 'Bridge', 'Deniz Feneri': 'Lighthouse',
  'Yel Değirmeni': 'Windmill', 'Çiftlik': 'Farm', 'Tren İstasyonu': 'Train Station',
  'Noel Ağacı': 'Christmas Tree', 'Cadılar Bayramı': 'Halloween', 'Paskalya': 'Easter',
  'Doğum Günü': 'Birthday', 'Kardan Adam': 'Snowman', 'Noel Baba': 'Santa Claus',
  'Balkabağı': 'Pumpkin', 'Sevgililer Günü': 'Valentine\'s Day', 'Havai Fişek': 'Fireworks',
  'Hediye Kutusu': 'Gift Box',
  'A - Aslan': 'A - Lion',
  'B - Balon': 'B - Balloon',
  'C - Cüzdan': 'C - Wallet',
  'Ç - Çiçek': 'Ç - Flower',
  'D - Davul': 'D - Drum',
  'E - Elma': 'E - Apple',
  'F - Fil': 'F - Elephant',
  'G - Gemi': 'G - Ship',
  'Ğ': 'Ğ',
  'H - Horoz': 'H - Rooster',
  'I - Iguana': 'I - Iguana',
  'İ - İnek': 'İ - Cow',
  'J - Jip': 'J - Jeep',
  'K - Kedi': 'K - Cat',
  'L - Lale': 'L - Tulip',
  'M - Maymun': 'M - Monkey',
  'N - Nar': 'N - Pomegranate',
  'O - Otobüs': 'O - Bus',
  'Ö - Ördek': 'Ö - Duck',
  'P - Papağan': 'P - Parrot',
  'R - Robot': 'R - Robot',
  'S - Salyangoz': 'S - Snail',
  'Ş - Şemsiye': 'Ş - Umbrella',
  'T - Tavşan': 'T - Rabbit',
  'U - Uçak': 'U - Airplane',
  'Ü - Üzüm': 'Ü - Grapes',
  'V - Vazo': 'V - Vase',
  'Y - Yıldız': 'Y - Star',
  'Z - Zürafa': 'Z - Giraffe',
  'A - Apple': 'A - Apple',
  'B - Ball': 'B - Ball',
  'C - Cat': 'C - Cat',
  'D - Dog': 'D - Dog',
  'E - Elephant': 'E - Elephant',
  'F - Fish': 'F - Fish',
  'G - Giraffe': 'G - Giraffe',
  'H - House': 'H - House',
  'I - Ice Cream': 'I - Ice Cream',
  'J - Jellyfish': 'J - Jellyfish',
  'K - Kite': 'K - Kite',
  'L - Lion': 'L - Lion',
  'M - Monkey': 'M - Monkey',
  'N - Nest': 'N - Nest',
  'O - Orange': 'O - Orange',
  'P - Pizza': 'P - Pizza',
  'Q - Queen': 'Q - Queen',
  'R - Rabbit': 'R - Rabbit',
  'S - Sun': 'S - Sun',
  'T - Tree': 'T - Tree',
  'U - Umbrella': 'U - Umbrella',
  'V - Violin': 'V - Violin',
  'W - Whale': 'W - Whale',
  'X - Xylophone': 'X - Xylophone',
  'Y - Yacht': 'Y - Yacht',
  'Z - Zebra': 'Z - Zebra',
  '1 - Bir': '1 - One',
  '2 - İki': '2 - Two',
  '3 - Üç': '3 - Three',
  '4 - Dört': '4 - Four',
  '5 - Beş': '5 - Five',
  '6 - Altı': '6 - Six',
  '7 - Yedi': '7 - Seven',
  '8 - Sekiz': '8 - Eight',
  '9 - Dokuz': '9 - Nine',
  '10 - On': '10 - Ten',
  'Merkür': 'Mercury',
  'Venüs': 'Venus',
  'Dünya': 'Earth',
  'Mars': 'Mars',
  'Uranüs': 'Uranus',
  'Neptün': 'Neptune',
};

export const STOCK_CATEGORIES: StockCategory[] = [
  {
    "id": "hayvanlar",
    "name": "Hayvanlar",
    "emoji": "🦁",
    "images": [
      {
        "id": "h01",
        "filename": "hayvanlar-01.png",
        "path": "/stock-coloring/hayvanlar/hayvanlar-01.png",
        "category": "hayvanlar",
        "title": "Sevimli Kedi"
      },
      {
        "id": "h02",
        "filename": "hayvanlar-02.png",
        "path": "/stock-coloring/hayvanlar/hayvanlar-02.png",
        "category": "hayvanlar",
        "title": "Neşeli Köpek"
      },
      {
        "id": "h03",
        "filename": "hayvanlar-03.png",
        "path": "/stock-coloring/hayvanlar/hayvanlar-03.png",
        "category": "hayvanlar",
        "title": "Cesur Aslan"
      },
      {
        "id": "h04",
        "filename": "hayvanlar-04.png",
        "path": "/stock-coloring/hayvanlar/hayvanlar-04.png",
        "category": "hayvanlar",
        "title": "Kocaman Fil"
      },
      {
        "id": "h05",
        "filename": "hayvanlar-05.png",
        "path": "/stock-coloring/hayvanlar/hayvanlar-05.png",
        "category": "hayvanlar",
        "title": "Güzel Kelebek"
      },
      {
        "id": "h06",
        "filename": "hayvanlar-06.png",
        "path": "/stock-coloring/hayvanlar/hayvanlar-06.png",
        "category": "hayvanlar",
        "title": "Şirin Tavşan"
      },
      {
        "id": "h07",
        "filename": "hayvanlar-07.png",
        "path": "/stock-coloring/hayvanlar/hayvanlar-07.png",
        "category": "hayvanlar",
        "title": "Renkli Balık"
      },
      {
        "id": "h08",
        "filename": "hayvanlar-08.png",
        "path": "/stock-coloring/hayvanlar/hayvanlar-08.png",
        "category": "hayvanlar",
        "title": "Ötücü Kuş"
      },
      {
        "id": "h09",
        "filename": "hayvanlar-09.png",
        "path": "/stock-coloring/hayvanlar/hayvanlar-09.png",
        "category": "hayvanlar",
        "title": "Zarif At"
      },
      {
        "id": "h10",
        "filename": "hayvanlar-10.png",
        "path": "/stock-coloring/hayvanlar/hayvanlar-10.png",
        "category": "hayvanlar",
        "title": "Tatlı Ayı"
      }
    ]
  },
  {
    "id": "uzay",
    "name": "Uzay",
    "emoji": "🚀",
    "images": [
      {
        "id": "u01",
        "filename": "uzay-01.png",
        "path": "/stock-coloring/uzay/uzay-01.png",
        "category": "uzay",
        "title": "Roket"
      },
      {
        "id": "u02",
        "filename": "uzay-02.png",
        "path": "/stock-coloring/uzay/uzay-02.png",
        "category": "uzay",
        "title": "Astronot"
      },
      {
        "id": "u03",
        "filename": "uzay-03.png",
        "path": "/stock-coloring/uzay/uzay-03.png",
        "category": "uzay",
        "title": "Gezegen"
      },
      {
        "id": "u04",
        "filename": "uzay-04.png",
        "path": "/stock-coloring/uzay/uzay-04.png",
        "category": "uzay",
        "title": "Yıldızlar"
      },
      {
        "id": "u05",
        "filename": "uzay-05.png",
        "path": "/stock-coloring/uzay/uzay-05.png",
        "category": "uzay",
        "title": "Uzaylı"
      },
      {
        "id": "u06",
        "filename": "uzay-06.png",
        "path": "/stock-coloring/uzay/uzay-06.png",
        "category": "uzay",
        "title": "Uzay Gemisi"
      },
      {
        "id": "u07",
        "filename": "uzay-07.png",
        "path": "/stock-coloring/uzay/uzay-07.png",
        "category": "uzay",
        "title": "Ay"
      },
      {
        "id": "u08",
        "filename": "uzay-08.png",
        "path": "/stock-coloring/uzay/uzay-08.png",
        "category": "uzay",
        "title": "Güneş"
      },
      {
        "id": "u09",
        "filename": "uzay-09.png",
        "path": "/stock-coloring/uzay/uzay-09.png",
        "category": "uzay",
        "title": "Satürn"
      },
      {
        "id": "u10",
        "filename": "uzay-10.png",
        "path": "/stock-coloring/uzay/uzay-10.png",
        "category": "uzay",
        "title": "UFO"
      }
    ]
  },
  {
    "id": "deniz",
    "name": "Deniz & Okyanus",
    "emoji": "🌊",
    "images": [
      {
        "id": "d01",
        "filename": "deniz-01.png",
        "path": "/stock-coloring/deniz/deniz-01.png",
        "category": "deniz",
        "title": "Balina"
      },
      {
        "id": "d02",
        "filename": "deniz-02.png",
        "path": "/stock-coloring/deniz/deniz-02.png",
        "category": "deniz",
        "title": "Yunus"
      },
      {
        "id": "d03",
        "filename": "deniz-03.png",
        "path": "/stock-coloring/deniz/deniz-03.png",
        "category": "deniz",
        "title": "Ahtapot"
      },
      {
        "id": "d04",
        "filename": "deniz-04.png",
        "path": "/stock-coloring/deniz/deniz-04.png",
        "category": "deniz",
        "title": "Deniz Atı"
      },
      {
        "id": "d05",
        "filename": "deniz-05.png",
        "path": "/stock-coloring/deniz/deniz-05.png",
        "category": "deniz",
        "title": "Kaplumbağa"
      },
      {
        "id": "d06",
        "filename": "deniz-06.png",
        "path": "/stock-coloring/deniz/deniz-06.png",
        "category": "deniz",
        "title": "Yengeç"
      },
      {
        "id": "d07",
        "filename": "deniz-07.png",
        "path": "/stock-coloring/deniz/deniz-07.png",
        "category": "deniz",
        "title": "Denizanası"
      },
      {
        "id": "d08",
        "filename": "deniz-08.png",
        "path": "/stock-coloring/deniz/deniz-08.png",
        "category": "deniz",
        "title": "Köpekbalığı"
      },
      {
        "id": "d09",
        "filename": "deniz-09.png",
        "path": "/stock-coloring/deniz/deniz-09.png",
        "category": "deniz",
        "title": "Deniz Kızı"
      },
      {
        "id": "d10",
        "filename": "deniz-10.png",
        "path": "/stock-coloring/deniz/deniz-10.png",
        "category": "deniz",
        "title": "Deniz Yıldızı"
      }
    ]
  },
  {
    "id": "masallar",
    "name": "Masallar & Fantazi",
    "emoji": "🏰",
    "images": [
      {
        "id": "m01",
        "filename": "masallar-01.png",
        "path": "/stock-coloring/masallar/masallar-01.png",
        "category": "masallar",
        "title": "Prenses"
      },
      {
        "id": "m02",
        "filename": "masallar-02.png",
        "path": "/stock-coloring/masallar/masallar-02.png",
        "category": "masallar",
        "title": "Kale"
      },
      {
        "id": "m03",
        "filename": "masallar-03.png",
        "path": "/stock-coloring/masallar/masallar-03.png",
        "category": "masallar",
        "title": "Ejderha"
      },
      {
        "id": "m04",
        "filename": "masallar-04.png",
        "path": "/stock-coloring/masallar/masallar-04.png",
        "category": "masallar",
        "title": "Unicorn"
      },
      {
        "id": "m05",
        "filename": "masallar-05.png",
        "path": "/stock-coloring/masallar/masallar-05.png",
        "category": "masallar",
        "title": "Peri"
      },
      {
        "id": "m06",
        "filename": "masallar-06.png",
        "path": "/stock-coloring/masallar/masallar-06.png",
        "category": "masallar",
        "title": "Şövalye"
      },
      {
        "id": "m07",
        "filename": "masallar-07.png",
        "path": "/stock-coloring/masallar/masallar-07.png",
        "category": "masallar",
        "title": "Büyücü"
      },
      {
        "id": "m08",
        "filename": "masallar-08.png",
        "path": "/stock-coloring/masallar/masallar-08.png",
        "category": "masallar",
        "title": "Taç"
      },
      {
        "id": "m09",
        "filename": "masallar-09.png",
        "path": "/stock-coloring/masallar/masallar-09.png",
        "category": "masallar",
        "title": "Sihirli Lamba"
      },
      {
        "id": "m10",
        "filename": "masallar-10.png",
        "path": "/stock-coloring/masallar/masallar-10.png",
        "category": "masallar",
        "title": "Korsan"
      }
    ]
  },
  {
    "id": "araclar",
    "name": "Araçlar & Taşıtlar",
    "emoji": "🚗",
    "images": [
      {
        "id": "a01",
        "filename": "araclar-01.png",
        "path": "/stock-coloring/araclar/araclar-01.png",
        "category": "araclar",
        "title": "Araba"
      },
      {
        "id": "a02",
        "filename": "araclar-02.png",
        "path": "/stock-coloring/araclar/araclar-02.png",
        "category": "araclar",
        "title": "Kamyon"
      },
      {
        "id": "a03",
        "filename": "araclar-03.png",
        "path": "/stock-coloring/araclar/araclar-03.png",
        "category": "araclar",
        "title": "Uçak"
      },
      {
        "id": "a04",
        "filename": "araclar-04.png",
        "path": "/stock-coloring/araclar/araclar-04.png",
        "category": "araclar",
        "title": "Tren"
      },
      {
        "id": "a05",
        "filename": "araclar-05.png",
        "path": "/stock-coloring/araclar/araclar-05.png",
        "category": "araclar",
        "title": "Helikopter"
      },
      {
        "id": "a06",
        "filename": "araclar-06.png",
        "path": "/stock-coloring/araclar/araclar-06.png",
        "category": "araclar",
        "title": "Gemi"
      },
      {
        "id": "a07",
        "filename": "araclar-07.png",
        "path": "/stock-coloring/araclar/araclar-07.png",
        "category": "araclar",
        "title": "Bisiklet"
      },
      {
        "id": "a08",
        "filename": "araclar-08.png",
        "path": "/stock-coloring/araclar/araclar-08.png",
        "category": "araclar",
        "title": "Otobüs"
      },
      {
        "id": "a09",
        "filename": "araclar-09.png",
        "path": "/stock-coloring/araclar/araclar-09.png",
        "category": "araclar",
        "title": "Motosiklet"
      },
      {
        "id": "a10",
        "filename": "araclar-10.png",
        "path": "/stock-coloring/araclar/araclar-10.png",
        "category": "araclar",
        "title": "İtfaiye"
      }
    ]
  },
  {
    "id": "doga",
    "name": "Doğa & Çiçekler",
    "emoji": "🌸",
    "images": [
      {
        "id": "d01",
        "filename": "doga-01.png",
        "path": "/stock-coloring/doga/doga-01.png",
        "category": "doga",
        "title": "Çiçek Bahçesi"
      },
      {
        "id": "d02",
        "filename": "doga-02.png",
        "path": "/stock-coloring/doga/doga-02.png",
        "category": "doga",
        "title": "Büyük Ağaç"
      },
      {
        "id": "d03",
        "filename": "doga-03.png",
        "path": "/stock-coloring/doga/doga-03.png",
        "category": "doga",
        "title": "Gökkuşağı"
      },
      {
        "id": "d04",
        "filename": "doga-04.png",
        "path": "/stock-coloring/doga/doga-04.png",
        "category": "doga",
        "title": "Dağ Manzarası"
      },
      {
        "id": "d05",
        "filename": "doga-05.png",
        "path": "/stock-coloring/doga/doga-05.png",
        "category": "doga",
        "title": "Şelale"
      },
      {
        "id": "d06",
        "filename": "doga-06.png",
        "path": "/stock-coloring/doga/doga-06.png",
        "category": "doga",
        "title": "Mantar"
      },
      {
        "id": "d07",
        "filename": "doga-07.png",
        "path": "/stock-coloring/doga/doga-07.png",
        "category": "doga",
        "title": "Yaprak"
      },
      {
        "id": "d08",
        "filename": "doga-08.png",
        "path": "/stock-coloring/doga/doga-08.png",
        "category": "doga",
        "title": "Gül"
      },
      {
        "id": "d09",
        "filename": "doga-09.png",
        "path": "/stock-coloring/doga/doga-09.png",
        "category": "doga",
        "title": "Ayçiçeği"
      },
      {
        "id": "d10",
        "filename": "doga-10.png",
        "path": "/stock-coloring/doga/doga-10.png",
        "category": "doga",
        "title": "Orman"
      }
    ]
  },
  {
    "id": "dinozorlar",
    "name": "Dinozorlar",
    "emoji": "🦕",
    "images": [
      {
        "id": "d01",
        "filename": "dinozorlar-01.png",
        "path": "/stock-coloring/dinozorlar/dinozorlar-01.png",
        "category": "dinozorlar",
        "title": "T-Rex"
      },
      {
        "id": "d02",
        "filename": "dinozorlar-02.png",
        "path": "/stock-coloring/dinozorlar/dinozorlar-02.png",
        "category": "dinozorlar",
        "title": "Triceratops"
      },
      {
        "id": "d03",
        "filename": "dinozorlar-03.png",
        "path": "/stock-coloring/dinozorlar/dinozorlar-03.png",
        "category": "dinozorlar",
        "title": "Stegosaurus"
      },
      {
        "id": "d04",
        "filename": "dinozorlar-04.png",
        "path": "/stock-coloring/dinozorlar/dinozorlar-04.png",
        "category": "dinozorlar",
        "title": "Pterodactyl"
      },
      {
        "id": "d05",
        "filename": "dinozorlar-05.png",
        "path": "/stock-coloring/dinozorlar/dinozorlar-05.png",
        "category": "dinozorlar",
        "title": "Brontosaurus"
      },
      {
        "id": "d06",
        "filename": "dinozorlar-06.png",
        "path": "/stock-coloring/dinozorlar/dinozorlar-06.png",
        "category": "dinozorlar",
        "title": "Raptor"
      },
      {
        "id": "d07",
        "filename": "dinozorlar-07.png",
        "path": "/stock-coloring/dinozorlar/dinozorlar-07.png",
        "category": "dinozorlar",
        "title": "Dinozor Yumurtası"
      },
      {
        "id": "d08",
        "filename": "dinozorlar-08.png",
        "path": "/stock-coloring/dinozorlar/dinozorlar-08.png",
        "category": "dinozorlar",
        "title": "Yanardağ"
      },
      {
        "id": "d09",
        "filename": "dinozorlar-09.png",
        "path": "/stock-coloring/dinozorlar/dinozorlar-09.png",
        "category": "dinozorlar",
        "title": "Bebek Dino"
      },
      {
        "id": "d10",
        "filename": "dinozorlar-10.png",
        "path": "/stock-coloring/dinozorlar/dinozorlar-10.png",
        "category": "dinozorlar",
        "title": "Dino Ailesi"
      }
    ]
  },
  {
    "id": "yiyecekler",
    "name": "Yiyecekler",
    "emoji": "🍕",
    "images": [
      {
        "id": "y01",
        "filename": "yiyecekler-01.png",
        "path": "/stock-coloring/yiyecekler/yiyecekler-01.png",
        "category": "yiyecekler",
        "title": "Pasta"
      },
      {
        "id": "y02",
        "filename": "yiyecekler-02.png",
        "path": "/stock-coloring/yiyecekler/yiyecekler-02.png",
        "category": "yiyecekler",
        "title": "Dondurma"
      },
      {
        "id": "y03",
        "filename": "yiyecekler-03.png",
        "path": "/stock-coloring/yiyecekler/yiyecekler-03.png",
        "category": "yiyecekler",
        "title": "Pizza"
      },
      {
        "id": "y04",
        "filename": "yiyecekler-04.png",
        "path": "/stock-coloring/yiyecekler/yiyecekler-04.png",
        "category": "yiyecekler",
        "title": "Meyveler"
      },
      {
        "id": "y05",
        "filename": "yiyecekler-05.png",
        "path": "/stock-coloring/yiyecekler/yiyecekler-05.png",
        "category": "yiyecekler",
        "title": "Cupcake"
      },
      {
        "id": "y06",
        "filename": "yiyecekler-06.png",
        "path": "/stock-coloring/yiyecekler/yiyecekler-06.png",
        "category": "yiyecekler",
        "title": "Kurabiye"
      },
      {
        "id": "y07",
        "filename": "yiyecekler-07.png",
        "path": "/stock-coloring/yiyecekler/yiyecekler-07.png",
        "category": "yiyecekler",
        "title": "Donut"
      },
      {
        "id": "y08",
        "filename": "yiyecekler-08.png",
        "path": "/stock-coloring/yiyecekler/yiyecekler-08.png",
        "category": "yiyecekler",
        "title": "Şeker"
      },
      {
        "id": "y09",
        "filename": "yiyecekler-09.png",
        "path": "/stock-coloring/yiyecekler/yiyecekler-09.png",
        "category": "yiyecekler",
        "title": "Hamburger"
      },
      {
        "id": "y10",
        "filename": "yiyecekler-10.png",
        "path": "/stock-coloring/yiyecekler/yiyecekler-10.png",
        "category": "yiyecekler",
        "title": "Karpuz"
      }
    ]
  },
  {
    "id": "sehir",
    "name": "Ev & Şehir",
    "emoji": "🏠",
    "images": [
      {
        "id": "s01",
        "filename": "sehir-01.png",
        "path": "/stock-coloring/sehir/sehir-01.png",
        "category": "sehir",
        "title": "Ev"
      },
      {
        "id": "s02",
        "filename": "sehir-02.png",
        "path": "/stock-coloring/sehir/sehir-02.png",
        "category": "sehir",
        "title": "Binalar"
      },
      {
        "id": "s03",
        "filename": "sehir-03.png",
        "path": "/stock-coloring/sehir/sehir-03.png",
        "category": "sehir",
        "title": "Okul"
      },
      {
        "id": "s04",
        "filename": "sehir-04.png",
        "path": "/stock-coloring/sehir/sehir-04.png",
        "category": "sehir",
        "title": "Oyun Parkı"
      },
      {
        "id": "s05",
        "filename": "sehir-05.png",
        "path": "/stock-coloring/sehir/sehir-05.png",
        "category": "sehir",
        "title": "Park"
      },
      {
        "id": "s06",
        "filename": "sehir-06.png",
        "path": "/stock-coloring/sehir/sehir-06.png",
        "category": "sehir",
        "title": "Köprü"
      },
      {
        "id": "s07",
        "filename": "sehir-07.png",
        "path": "/stock-coloring/sehir/sehir-07.png",
        "category": "sehir",
        "title": "Deniz Feneri"
      },
      {
        "id": "s08",
        "filename": "sehir-08.png",
        "path": "/stock-coloring/sehir/sehir-08.png",
        "category": "sehir",
        "title": "Yel Değirmeni"
      },
      {
        "id": "s09",
        "filename": "sehir-09.png",
        "path": "/stock-coloring/sehir/sehir-09.png",
        "category": "sehir",
        "title": "Çiftlik"
      },
      {
        "id": "s10",
        "filename": "sehir-10.png",
        "path": "/stock-coloring/sehir/sehir-10.png",
        "category": "sehir",
        "title": "Tren İstasyonu"
      }
    ]
  },
  {
    "id": "tatil",
    "name": "Tatil & Özel Günler",
    "emoji": "🎄",
    "images": [
      {
        "id": "t01",
        "filename": "tatil-01.png",
        "path": "/stock-coloring/tatil/tatil-01.png",
        "category": "tatil",
        "title": "Noel Ağacı"
      },
      {
        "id": "t02",
        "filename": "tatil-02.png",
        "path": "/stock-coloring/tatil/tatil-02.png",
        "category": "tatil",
        "title": "Cadılar Bayramı"
      },
      {
        "id": "t03",
        "filename": "tatil-03.png",
        "path": "/stock-coloring/tatil/tatil-03.png",
        "category": "tatil",
        "title": "Paskalya"
      },
      {
        "id": "t04",
        "filename": "tatil-04.png",
        "path": "/stock-coloring/tatil/tatil-04.png",
        "category": "tatil",
        "title": "Doğum Günü"
      },
      {
        "id": "t05",
        "filename": "tatil-05.png",
        "path": "/stock-coloring/tatil/tatil-05.png",
        "category": "tatil",
        "title": "Kardan Adam"
      },
      {
        "id": "t06",
        "filename": "tatil-06.png",
        "path": "/stock-coloring/tatil/tatil-06.png",
        "category": "tatil",
        "title": "Noel Baba"
      },
      {
        "id": "t07",
        "filename": "tatil-07.png",
        "path": "/stock-coloring/tatil/tatil-07.png",
        "category": "tatil",
        "title": "Balkabağı"
      },
      {
        "id": "t08",
        "filename": "tatil-08.png",
        "path": "/stock-coloring/tatil/tatil-08.png",
        "category": "tatil",
        "title": "Sevgililer Günü"
      },
      {
        "id": "t09",
        "filename": "tatil-09.png",
        "path": "/stock-coloring/tatil/tatil-09.png",
        "category": "tatil",
        "title": "Havai Fişek"
      },
      {
        "id": "t10",
        "filename": "tatil-10.png",
        "path": "/stock-coloring/tatil/tatil-10.png",
        "category": "tatil",
        "title": "Hediye Kutusu"
      }
    ]
  }
,
  {
  "id": "alfabe",
  "name": "Alfabe",
  "emoji": "🔤",
  "images": [
    {
      "id": "al01",
      "filename": "alfabe-A.png",
      "path": "/stock-coloring/alfabe/alfabe-A.png",
      "category": "alfabe",
      "title": "A - Aslan"
    },
    {
      "id": "al02",
      "filename": "alfabe-B.png",
      "path": "/stock-coloring/alfabe/alfabe-B.png",
      "category": "alfabe",
      "title": "B - Balon"
    },
    {
      "id": "al03",
      "filename": "alfabe-C.png",
      "path": "/stock-coloring/alfabe/alfabe-C.png",
      "category": "alfabe",
      "title": "C - Cüzdan"
    },
    {
      "id": "al04",
      "filename": "alfabe-C-ced.png",
      "path": "/stock-coloring/alfabe/alfabe-C-ced.png",
      "category": "alfabe",
      "title": "Ç - Çiçek"
    },
    {
      "id": "al05",
      "filename": "alfabe-D.png",
      "path": "/stock-coloring/alfabe/alfabe-D.png",
      "category": "alfabe",
      "title": "D - Davul"
    },
    {
      "id": "al06",
      "filename": "alfabe-E.png",
      "path": "/stock-coloring/alfabe/alfabe-E.png",
      "category": "alfabe",
      "title": "E - Elma"
    },
    {
      "id": "al07",
      "filename": "alfabe-F.png",
      "path": "/stock-coloring/alfabe/alfabe-F.png",
      "category": "alfabe",
      "title": "F - Fil"
    },
    {
      "id": "al08",
      "filename": "alfabe-G.png",
      "path": "/stock-coloring/alfabe/alfabe-G.png",
      "category": "alfabe",
      "title": "G - Gemi"
    },
    {
      "id": "al09",
      "filename": "alfabe-G-soft.png",
      "path": "/stock-coloring/alfabe/alfabe-G-soft.png",
      "category": "alfabe",
      "title": "Ğ"
    },
    {
      "id": "al10",
      "filename": "alfabe-H.png",
      "path": "/stock-coloring/alfabe/alfabe-H.png",
      "category": "alfabe",
      "title": "H - Horoz"
    },
    {
      "id": "al11",
      "filename": "alfabe-I.png",
      "path": "/stock-coloring/alfabe/alfabe-I.png",
      "category": "alfabe",
      "title": "I - Iguana"
    },
    {
      "id": "al12",
      "filename": "alfabe-I-dot.png",
      "path": "/stock-coloring/alfabe/alfabe-I-dot.png",
      "category": "alfabe",
      "title": "İ - İnek"
    },
    {
      "id": "al13",
      "filename": "alfabe-J.png",
      "path": "/stock-coloring/alfabe/alfabe-J.png",
      "category": "alfabe",
      "title": "J - Jip"
    },
    {
      "id": "al14",
      "filename": "alfabe-K.png",
      "path": "/stock-coloring/alfabe/alfabe-K.png",
      "category": "alfabe",
      "title": "K - Kedi"
    },
    {
      "id": "al15",
      "filename": "alfabe-L.png",
      "path": "/stock-coloring/alfabe/alfabe-L.png",
      "category": "alfabe",
      "title": "L - Lale"
    },
    {
      "id": "al16",
      "filename": "alfabe-M.png",
      "path": "/stock-coloring/alfabe/alfabe-M.png",
      "category": "alfabe",
      "title": "M - Maymun"
    },
    {
      "id": "al17",
      "filename": "alfabe-N.png",
      "path": "/stock-coloring/alfabe/alfabe-N.png",
      "category": "alfabe",
      "title": "N - Nar"
    },
    {
      "id": "al18",
      "filename": "alfabe-O.png",
      "path": "/stock-coloring/alfabe/alfabe-O.png",
      "category": "alfabe",
      "title": "O - Otobüs"
    },
    {
      "id": "al19",
      "filename": "alfabe-O-uml.png",
      "path": "/stock-coloring/alfabe/alfabe-O-uml.png",
      "category": "alfabe",
      "title": "Ö - Ördek"
    },
    {
      "id": "al20",
      "filename": "alfabe-P.png",
      "path": "/stock-coloring/alfabe/alfabe-P.png",
      "category": "alfabe",
      "title": "P - Papağan"
    },
    {
      "id": "al21",
      "filename": "alfabe-R.png",
      "path": "/stock-coloring/alfabe/alfabe-R.png",
      "category": "alfabe",
      "title": "R - Robot"
    },
    {
      "id": "al22",
      "filename": "alfabe-S.png",
      "path": "/stock-coloring/alfabe/alfabe-S.png",
      "category": "alfabe",
      "title": "S - Salyangoz"
    },
    {
      "id": "al23",
      "filename": "alfabe-S-ced.png",
      "path": "/stock-coloring/alfabe/alfabe-S-ced.png",
      "category": "alfabe",
      "title": "Ş - Şemsiye"
    },
    {
      "id": "al24",
      "filename": "alfabe-T.png",
      "path": "/stock-coloring/alfabe/alfabe-T.png",
      "category": "alfabe",
      "title": "T - Tavşan"
    },
    {
      "id": "al25",
      "filename": "alfabe-U.png",
      "path": "/stock-coloring/alfabe/alfabe-U.png",
      "category": "alfabe",
      "title": "U - Uçak"
    },
    {
      "id": "al26",
      "filename": "alfabe-U-uml.png",
      "path": "/stock-coloring/alfabe/alfabe-U-uml.png",
      "category": "alfabe",
      "title": "Ü - Üzüm"
    },
    {
      "id": "al27",
      "filename": "alfabe-V.png",
      "path": "/stock-coloring/alfabe/alfabe-V.png",
      "category": "alfabe",
      "title": "V - Vazo"
    },
    {
      "id": "al28",
      "filename": "alfabe-Y.png",
      "path": "/stock-coloring/alfabe/alfabe-Y.png",
      "category": "alfabe",
      "title": "Y - Yıldız"
    },
    {
      "id": "al29",
      "filename": "alfabe-Z.png",
      "path": "/stock-coloring/alfabe/alfabe-Z.png",
      "category": "alfabe",
      "title": "Z - Zürafa"
    }
  ]
},
  {
  "id": "sayilar",
  "name": "Sayılar",
  "emoji": "🔢",
  "images": [
    {
      "id": "sa01",
      "filename": "sayilar-01.png",
      "path": "/stock-coloring/sayilar/sayilar-01.png",
      "category": "sayilar",
      "title": "1 - Bir"
    },
    {
      "id": "sa02",
      "filename": "sayilar-02.png",
      "path": "/stock-coloring/sayilar/sayilar-02.png",
      "category": "sayilar",
      "title": "2 - İki"
    },
    {
      "id": "sa03",
      "filename": "sayilar-03.png",
      "path": "/stock-coloring/sayilar/sayilar-03.png",
      "category": "sayilar",
      "title": "3 - Üç"
    },
    {
      "id": "sa04",
      "filename": "sayilar-04.png",
      "path": "/stock-coloring/sayilar/sayilar-04.png",
      "category": "sayilar",
      "title": "4 - Dört"
    },
    {
      "id": "sa05",
      "filename": "sayilar-05.png",
      "path": "/stock-coloring/sayilar/sayilar-05.png",
      "category": "sayilar",
      "title": "5 - Beş"
    },
    {
      "id": "sa06",
      "filename": "sayilar-06.png",
      "path": "/stock-coloring/sayilar/sayilar-06.png",
      "category": "sayilar",
      "title": "6 - Altı"
    },
    {
      "id": "sa07",
      "filename": "sayilar-07.png",
      "path": "/stock-coloring/sayilar/sayilar-07.png",
      "category": "sayilar",
      "title": "7 - Yedi"
    },
    {
      "id": "sa08",
      "filename": "sayilar-08.png",
      "path": "/stock-coloring/sayilar/sayilar-08.png",
      "category": "sayilar",
      "title": "8 - Sekiz"
    },
    {
      "id": "sa09",
      "filename": "sayilar-09.png",
      "path": "/stock-coloring/sayilar/sayilar-09.png",
      "category": "sayilar",
      "title": "9 - Dokuz"
    },
    {
      "id": "sa10",
      "filename": "sayilar-10.png",
      "path": "/stock-coloring/sayilar/sayilar-10.png",
      "category": "sayilar",
      "title": "10 - On"
    }
  ]
},
  {
  "id": "gezegenler",
  "name": "Gezegenler",
  "emoji": "🪐",
  "images": [
    {
      "id": "ge01",
      "filename": "gezegenler-01.png",
      "path": "/stock-coloring/gezegenler/gezegenler-01.png",
      "category": "gezegenler",
      "title": "Güneş"
    },
    {
      "id": "ge02",
      "filename": "gezegenler-02.png",
      "path": "/stock-coloring/gezegenler/gezegenler-02.png",
      "category": "gezegenler",
      "title": "Merkür"
    },
    {
      "id": "ge03",
      "filename": "gezegenler-03.png",
      "path": "/stock-coloring/gezegenler/gezegenler-03.png",
      "category": "gezegenler",
      "title": "Venüs"
    },
    {
      "id": "ge04",
      "filename": "gezegenler-04.png",
      "path": "/stock-coloring/gezegenler/gezegenler-04.png",
      "category": "gezegenler",
      "title": "Dünya"
    },
    {
      "id": "ge05",
      "filename": "gezegenler-05.png",
      "path": "/stock-coloring/gezegenler/gezegenler-05.png",
      "category": "gezegenler",
      "title": "Mars"
    },
    {
      "id": "ge06",
      "filename": "gezegenler-06.png",
      "path": "/stock-coloring/gezegenler/gezegenler-06.png",
      "category": "gezegenler",
      "title": "Jüpiter"
    },
    {
      "id": "ge07",
      "filename": "gezegenler-07.png",
      "path": "/stock-coloring/gezegenler/gezegenler-07.png",
      "category": "gezegenler",
      "title": "Satürn"
    },
    {
      "id": "ge08",
      "filename": "gezegenler-08.png",
      "path": "/stock-coloring/gezegenler/gezegenler-08.png",
      "category": "gezegenler",
      "title": "Uranüs"
    },
    {
      "id": "ge09",
      "filename": "gezegenler-09.png",
      "path": "/stock-coloring/gezegenler/gezegenler-09.png",
      "category": "gezegenler",
      "title": "Neptün"
    },
    {
      "id": "ge10",
      "filename": "gezegenler-10.png",
      "path": "/stock-coloring/gezegenler/gezegenler-10.png",
      "category": "gezegenler",
      "title": "Ay"
    }
  ]
}
,
  {
  "id": "alphabet",
  "name": "Alphabet",
  "emoji": "🔤",
  "images": [
    {
      "id": "enA",
      "filename": "alphabet-A.png",
      "path": "/stock-coloring/alphabet/alphabet-A.png",
      "category": "alphabet",
      "title": "A - Apple"
    },
    {
      "id": "enB",
      "filename": "alphabet-B.png",
      "path": "/stock-coloring/alphabet/alphabet-B.png",
      "category": "alphabet",
      "title": "B - Ball"
    },
    {
      "id": "enC",
      "filename": "alphabet-C.png",
      "path": "/stock-coloring/alphabet/alphabet-C.png",
      "category": "alphabet",
      "title": "C - Cat"
    },
    {
      "id": "enD",
      "filename": "alphabet-D.png",
      "path": "/stock-coloring/alphabet/alphabet-D.png",
      "category": "alphabet",
      "title": "D - Dog"
    },
    {
      "id": "enE",
      "filename": "alphabet-E.png",
      "path": "/stock-coloring/alphabet/alphabet-E.png",
      "category": "alphabet",
      "title": "E - Elephant"
    },
    {
      "id": "enF",
      "filename": "alphabet-F.png",
      "path": "/stock-coloring/alphabet/alphabet-F.png",
      "category": "alphabet",
      "title": "F - Fish"
    },
    {
      "id": "enG",
      "filename": "alphabet-G.png",
      "path": "/stock-coloring/alphabet/alphabet-G.png",
      "category": "alphabet",
      "title": "G - Giraffe"
    },
    {
      "id": "enH",
      "filename": "alphabet-H.png",
      "path": "/stock-coloring/alphabet/alphabet-H.png",
      "category": "alphabet",
      "title": "H - House"
    },
    {
      "id": "enI",
      "filename": "alphabet-I.png",
      "path": "/stock-coloring/alphabet/alphabet-I.png",
      "category": "alphabet",
      "title": "I - Ice Cream"
    },
    {
      "id": "enJ",
      "filename": "alphabet-J.png",
      "path": "/stock-coloring/alphabet/alphabet-J.png",
      "category": "alphabet",
      "title": "J - Jellyfish"
    },
    {
      "id": "enK",
      "filename": "alphabet-K.png",
      "path": "/stock-coloring/alphabet/alphabet-K.png",
      "category": "alphabet",
      "title": "K - Kite"
    },
    {
      "id": "enL",
      "filename": "alphabet-L.png",
      "path": "/stock-coloring/alphabet/alphabet-L.png",
      "category": "alphabet",
      "title": "L - Lion"
    },
    {
      "id": "enM",
      "filename": "alphabet-M.png",
      "path": "/stock-coloring/alphabet/alphabet-M.png",
      "category": "alphabet",
      "title": "M - Monkey"
    },
    {
      "id": "enN",
      "filename": "alphabet-N.png",
      "path": "/stock-coloring/alphabet/alphabet-N.png",
      "category": "alphabet",
      "title": "N - Nest"
    },
    {
      "id": "enO",
      "filename": "alphabet-O.png",
      "path": "/stock-coloring/alphabet/alphabet-O.png",
      "category": "alphabet",
      "title": "O - Orange"
    },
    {
      "id": "enP",
      "filename": "alphabet-P.png",
      "path": "/stock-coloring/alphabet/alphabet-P.png",
      "category": "alphabet",
      "title": "P - Pizza"
    },
    {
      "id": "enQ",
      "filename": "alphabet-Q.png",
      "path": "/stock-coloring/alphabet/alphabet-Q.png",
      "category": "alphabet",
      "title": "Q - Queen"
    },
    {
      "id": "enR",
      "filename": "alphabet-R.png",
      "path": "/stock-coloring/alphabet/alphabet-R.png",
      "category": "alphabet",
      "title": "R - Rabbit"
    },
    {
      "id": "enS",
      "filename": "alphabet-S.png",
      "path": "/stock-coloring/alphabet/alphabet-S.png",
      "category": "alphabet",
      "title": "S - Sun"
    },
    {
      "id": "enT",
      "filename": "alphabet-T.png",
      "path": "/stock-coloring/alphabet/alphabet-T.png",
      "category": "alphabet",
      "title": "T - Tree"
    },
    {
      "id": "enU",
      "filename": "alphabet-U.png",
      "path": "/stock-coloring/alphabet/alphabet-U.png",
      "category": "alphabet",
      "title": "U - Umbrella"
    },
    {
      "id": "enV",
      "filename": "alphabet-V.png",
      "path": "/stock-coloring/alphabet/alphabet-V.png",
      "category": "alphabet",
      "title": "V - Violin"
    },
    {
      "id": "enW",
      "filename": "alphabet-W.png",
      "path": "/stock-coloring/alphabet/alphabet-W.png",
      "category": "alphabet",
      "title": "W - Whale"
    },
    {
      "id": "enX",
      "filename": "alphabet-X.png",
      "path": "/stock-coloring/alphabet/alphabet-X.png",
      "category": "alphabet",
      "title": "X - Xylophone"
    },
    {
      "id": "enY",
      "filename": "alphabet-Y.png",
      "path": "/stock-coloring/alphabet/alphabet-Y.png",
      "category": "alphabet",
      "title": "Y - Yacht"
    },
    {
      "id": "enZ",
      "filename": "alphabet-Z.png",
      "path": "/stock-coloring/alphabet/alphabet-Z.png",
      "category": "alphabet",
      "title": "Z - Zebra"
    }
  ]
}
];

export function getStockCategory(id: string): StockCategory | undefined {
  return STOCK_CATEGORIES.find((c) => c.id === id);
}

export function getAllStockImages(): StockImage[] {
  return STOCK_CATEGORIES.flatMap((c) => c.images);
}
