// Auto-generated by scripts/generate-stock.js
// Do not edit manually

export interface StockImage {
  id: string;
  filename: string;
  path: string;
  category: string;
  title: string;
}

export interface StockCategory {
  id: string;
  name: string;
  emoji: string;
  images: StockImage[];
}

export const STOCK_CATEGORIES: StockCategory[] = [
  {
    "id": "hayvanlar",
    "name": "Hayvanlar",
    "emoji": "🦁",
    "images": [
      {
        "id": "h01",
        "filename": "hayvanlar-01.png",
        "path": "/stock-coloring/hayvanlar/hayvanlar-01.png",
        "category": "hayvanlar",
        "title": "Sevimli Kedi"
      },
      {
        "id": "h02",
        "filename": "hayvanlar-02.png",
        "path": "/stock-coloring/hayvanlar/hayvanlar-02.png",
        "category": "hayvanlar",
        "title": "Neşeli Köpek"
      },
      {
        "id": "h03",
        "filename": "hayvanlar-03.png",
        "path": "/stock-coloring/hayvanlar/hayvanlar-03.png",
        "category": "hayvanlar",
        "title": "Cesur Aslan"
      },
      {
        "id": "h04",
        "filename": "hayvanlar-04.png",
        "path": "/stock-coloring/hayvanlar/hayvanlar-04.png",
        "category": "hayvanlar",
        "title": "Kocaman Fil"
      },
      {
        "id": "h05",
        "filename": "hayvanlar-05.png",
        "path": "/stock-coloring/hayvanlar/hayvanlar-05.png",
        "category": "hayvanlar",
        "title": "Güzel Kelebek"
      },
      {
        "id": "h06",
        "filename": "hayvanlar-06.png",
        "path": "/stock-coloring/hayvanlar/hayvanlar-06.png",
        "category": "hayvanlar",
        "title": "Şirin Tavşan"
      },
      {
        "id": "h07",
        "filename": "hayvanlar-07.png",
        "path": "/stock-coloring/hayvanlar/hayvanlar-07.png",
        "category": "hayvanlar",
        "title": "Renkli Balık"
      },
      {
        "id": "h08",
        "filename": "hayvanlar-08.png",
        "path": "/stock-coloring/hayvanlar/hayvanlar-08.png",
        "category": "hayvanlar",
        "title": "Ötücü Kuş"
      },
      {
        "id": "h09",
        "filename": "hayvanlar-09.png",
        "path": "/stock-coloring/hayvanlar/hayvanlar-09.png",
        "category": "hayvanlar",
        "title": "Zarif At"
      },
      {
        "id": "h10",
        "filename": "hayvanlar-10.png",
        "path": "/stock-coloring/hayvanlar/hayvanlar-10.png",
        "category": "hayvanlar",
        "title": "Tatlı Ayı"
      }
    ]
  },
  {
    "id": "uzay",
    "name": "Uzay",
    "emoji": "🚀",
    "images": [
      {
        "id": "u01",
        "filename": "uzay-01.png",
        "path": "/stock-coloring/uzay/uzay-01.png",
        "category": "uzay",
        "title": "Roket"
      },
      {
        "id": "u02",
        "filename": "uzay-02.png",
        "path": "/stock-coloring/uzay/uzay-02.png",
        "category": "uzay",
        "title": "Astronot"
      },
      {
        "id": "u03",
        "filename": "uzay-03.png",
        "path": "/stock-coloring/uzay/uzay-03.png",
        "category": "uzay",
        "title": "Gezegen"
      },
      {
        "id": "u04",
        "filename": "uzay-04.png",
        "path": "/stock-coloring/uzay/uzay-04.png",
        "category": "uzay",
        "title": "Yıldızlar"
      },
      {
        "id": "u05",
        "filename": "uzay-05.png",
        "path": "/stock-coloring/uzay/uzay-05.png",
        "category": "uzay",
        "title": "Uzaylı"
      },
      {
        "id": "u06",
        "filename": "uzay-06.png",
        "path": "/stock-coloring/uzay/uzay-06.png",
        "category": "uzay",
        "title": "Uzay Gemisi"
      },
      {
        "id": "u07",
        "filename": "uzay-07.png",
        "path": "/stock-coloring/uzay/uzay-07.png",
        "category": "uzay",
        "title": "Ay"
      },
      {
        "id": "u08",
        "filename": "uzay-08.png",
        "path": "/stock-coloring/uzay/uzay-08.png",
        "category": "uzay",
        "title": "Güneş"
      },
      {
        "id": "u09",
        "filename": "uzay-09.png",
        "path": "/stock-coloring/uzay/uzay-09.png",
        "category": "uzay",
        "title": "Satürn"
      },
      {
        "id": "u10",
        "filename": "uzay-10.png",
        "path": "/stock-coloring/uzay/uzay-10.png",
        "category": "uzay",
        "title": "UFO"
      }
    ]
  },
  {
    "id": "deniz",
    "name": "Deniz & Okyanus",
    "emoji": "🌊",
    "images": [
      {
        "id": "d01",
        "filename": "deniz-01.png",
        "path": "/stock-coloring/deniz/deniz-01.png",
        "category": "deniz",
        "title": "Balina"
      },
      {
        "id": "d02",
        "filename": "deniz-02.png",
        "path": "/stock-coloring/deniz/deniz-02.png",
        "category": "deniz",
        "title": "Yunus"
      },
      {
        "id": "d03",
        "filename": "deniz-03.png",
        "path": "/stock-coloring/deniz/deniz-03.png",
        "category": "deniz",
        "title": "Ahtapot"
      },
      {
        "id": "d04",
        "filename": "deniz-04.png",
        "path": "/stock-coloring/deniz/deniz-04.png",
        "category": "deniz",
        "title": "Deniz Atı"
      },
      {
        "id": "d05",
        "filename": "deniz-05.png",
        "path": "/stock-coloring/deniz/deniz-05.png",
        "category": "deniz",
        "title": "Kaplumbağa"
      },
      {
        "id": "d06",
        "filename": "deniz-06.png",
        "path": "/stock-coloring/deniz/deniz-06.png",
        "category": "deniz",
        "title": "Yengeç"
      },
      {
        "id": "d07",
        "filename": "deniz-07.png",
        "path": "/stock-coloring/deniz/deniz-07.png",
        "category": "deniz",
        "title": "Denizanası"
      },
      {
        "id": "d08",
        "filename": "deniz-08.png",
        "path": "/stock-coloring/deniz/deniz-08.png",
        "category": "deniz",
        "title": "Köpekbalığı"
      },
      {
        "id": "d09",
        "filename": "deniz-09.png",
        "path": "/stock-coloring/deniz/deniz-09.png",
        "category": "deniz",
        "title": "Deniz Kızı"
      },
      {
        "id": "d10",
        "filename": "deniz-10.png",
        "path": "/stock-coloring/deniz/deniz-10.png",
        "category": "deniz",
        "title": "Deniz Yıldızı"
      }
    ]
  },
  {
    "id": "masallar",
    "name": "Masallar & Fantazi",
    "emoji": "🏰",
    "images": [
      {
        "id": "m01",
        "filename": "masallar-01.png",
        "path": "/stock-coloring/masallar/masallar-01.png",
        "category": "masallar",
        "title": "Prenses"
      },
      {
        "id": "m02",
        "filename": "masallar-02.png",
        "path": "/stock-coloring/masallar/masallar-02.png",
        "category": "masallar",
        "title": "Kale"
      },
      {
        "id": "m03",
        "filename": "masallar-03.png",
        "path": "/stock-coloring/masallar/masallar-03.png",
        "category": "masallar",
        "title": "Ejderha"
      },
      {
        "id": "m04",
        "filename": "masallar-04.png",
        "path": "/stock-coloring/masallar/masallar-04.png",
        "category": "masallar",
        "title": "Unicorn"
      },
      {
        "id": "m05",
        "filename": "masallar-05.png",
        "path": "/stock-coloring/masallar/masallar-05.png",
        "category": "masallar",
        "title": "Peri"
      },
      {
        "id": "m06",
        "filename": "masallar-06.png",
        "path": "/stock-coloring/masallar/masallar-06.png",
        "category": "masallar",
        "title": "Şövalye"
      },
      {
        "id": "m07",
        "filename": "masallar-07.png",
        "path": "/stock-coloring/masallar/masallar-07.png",
        "category": "masallar",
        "title": "Büyücü"
      },
      {
        "id": "m08",
        "filename": "masallar-08.png",
        "path": "/stock-coloring/masallar/masallar-08.png",
        "category": "masallar",
        "title": "Taç"
      },
      {
        "id": "m09",
        "filename": "masallar-09.png",
        "path": "/stock-coloring/masallar/masallar-09.png",
        "category": "masallar",
        "title": "Sihirli Lamba"
      },
      {
        "id": "m10",
        "filename": "masallar-10.png",
        "path": "/stock-coloring/masallar/masallar-10.png",
        "category": "masallar",
        "title": "Korsan"
      }
    ]
  },
  {
    "id": "araclar",
    "name": "Araçlar & Taşıtlar",
    "emoji": "🚗",
    "images": [
      {
        "id": "a01",
        "filename": "araclar-01.png",
        "path": "/stock-coloring/araclar/araclar-01.png",
        "category": "araclar",
        "title": "Araba"
      },
      {
        "id": "a02",
        "filename": "araclar-02.png",
        "path": "/stock-coloring/araclar/araclar-02.png",
        "category": "araclar",
        "title": "Kamyon"
      },
      {
        "id": "a03",
        "filename": "araclar-03.png",
        "path": "/stock-coloring/araclar/araclar-03.png",
        "category": "araclar",
        "title": "Uçak"
      },
      {
        "id": "a04",
        "filename": "araclar-04.png",
        "path": "/stock-coloring/araclar/araclar-04.png",
        "category": "araclar",
        "title": "Tren"
      },
      {
        "id": "a05",
        "filename": "araclar-05.png",
        "path": "/stock-coloring/araclar/araclar-05.png",
        "category": "araclar",
        "title": "Helikopter"
      },
      {
        "id": "a06",
        "filename": "araclar-06.png",
        "path": "/stock-coloring/araclar/araclar-06.png",
        "category": "araclar",
        "title": "Gemi"
      },
      {
        "id": "a07",
        "filename": "araclar-07.png",
        "path": "/stock-coloring/araclar/araclar-07.png",
        "category": "araclar",
        "title": "Bisiklet"
      },
      {
        "id": "a08",
        "filename": "araclar-08.png",
        "path": "/stock-coloring/araclar/araclar-08.png",
        "category": "araclar",
        "title": "Otobüs"
      },
      {
        "id": "a09",
        "filename": "araclar-09.png",
        "path": "/stock-coloring/araclar/araclar-09.png",
        "category": "araclar",
        "title": "Motosiklet"
      },
      {
        "id": "a10",
        "filename": "araclar-10.png",
        "path": "/stock-coloring/araclar/araclar-10.png",
        "category": "araclar",
        "title": "İtfaiye"
      }
    ]
  },
  {
    "id": "doga",
    "name": "Doğa & Çiçekler",
    "emoji": "🌸",
    "images": [
      {
        "id": "d01",
        "filename": "doga-01.png",
        "path": "/stock-coloring/doga/doga-01.png",
        "category": "doga",
        "title": "Çiçek Bahçesi"
      },
      {
        "id": "d02",
        "filename": "doga-02.png",
        "path": "/stock-coloring/doga/doga-02.png",
        "category": "doga",
        "title": "Büyük Ağaç"
      },
      {
        "id": "d03",
        "filename": "doga-03.png",
        "path": "/stock-coloring/doga/doga-03.png",
        "category": "doga",
        "title": "Gökkuşağı"
      },
      {
        "id": "d04",
        "filename": "doga-04.png",
        "path": "/stock-coloring/doga/doga-04.png",
        "category": "doga",
        "title": "Dağ Manzarası"
      },
      {
        "id": "d05",
        "filename": "doga-05.png",
        "path": "/stock-coloring/doga/doga-05.png",
        "category": "doga",
        "title": "Şelale"
      },
      {
        "id": "d06",
        "filename": "doga-06.png",
        "path": "/stock-coloring/doga/doga-06.png",
        "category": "doga",
        "title": "Mantar"
      },
      {
        "id": "d07",
        "filename": "doga-07.png",
        "path": "/stock-coloring/doga/doga-07.png",
        "category": "doga",
        "title": "Yaprak"
      },
      {
        "id": "d08",
        "filename": "doga-08.png",
        "path": "/stock-coloring/doga/doga-08.png",
        "category": "doga",
        "title": "Gül"
      },
      {
        "id": "d09",
        "filename": "doga-09.png",
        "path": "/stock-coloring/doga/doga-09.png",
        "category": "doga",
        "title": "Ayçiçeği"
      },
      {
        "id": "d10",
        "filename": "doga-10.png",
        "path": "/stock-coloring/doga/doga-10.png",
        "category": "doga",
        "title": "Orman"
      }
    ]
  },
  {
    "id": "dinozorlar",
    "name": "Dinozorlar",
    "emoji": "🦕",
    "images": [
      {
        "id": "d01",
        "filename": "dinozorlar-01.png",
        "path": "/stock-coloring/dinozorlar/dinozorlar-01.png",
        "category": "dinozorlar",
        "title": "T-Rex"
      },
      {
        "id": "d02",
        "filename": "dinozorlar-02.png",
        "path": "/stock-coloring/dinozorlar/dinozorlar-02.png",
        "category": "dinozorlar",
        "title": "Triceratops"
      },
      {
        "id": "d03",
        "filename": "dinozorlar-03.png",
        "path": "/stock-coloring/dinozorlar/dinozorlar-03.png",
        "category": "dinozorlar",
        "title": "Stegosaurus"
      },
      {
        "id": "d04",
        "filename": "dinozorlar-04.png",
        "path": "/stock-coloring/dinozorlar/dinozorlar-04.png",
        "category": "dinozorlar",
        "title": "Pterodactyl"
      },
      {
        "id": "d05",
        "filename": "dinozorlar-05.png",
        "path": "/stock-coloring/dinozorlar/dinozorlar-05.png",
        "category": "dinozorlar",
        "title": "Brontosaurus"
      },
      {
        "id": "d06",
        "filename": "dinozorlar-06.png",
        "path": "/stock-coloring/dinozorlar/dinozorlar-06.png",
        "category": "dinozorlar",
        "title": "Raptor"
      },
      {
        "id": "d07",
        "filename": "dinozorlar-07.png",
        "path": "/stock-coloring/dinozorlar/dinozorlar-07.png",
        "category": "dinozorlar",
        "title": "Dinozor Yumurtası"
      },
      {
        "id": "d08",
        "filename": "dinozorlar-08.png",
        "path": "/stock-coloring/dinozorlar/dinozorlar-08.png",
        "category": "dinozorlar",
        "title": "Yanardağ"
      },
      {
        "id": "d09",
        "filename": "dinozorlar-09.png",
        "path": "/stock-coloring/dinozorlar/dinozorlar-09.png",
        "category": "dinozorlar",
        "title": "Bebek Dino"
      },
      {
        "id": "d10",
        "filename": "dinozorlar-10.png",
        "path": "/stock-coloring/dinozorlar/dinozorlar-10.png",
        "category": "dinozorlar",
        "title": "Dino Ailesi"
      }
    ]
  },
  {
    "id": "yiyecekler",
    "name": "Yiyecekler",
    "emoji": "🍕",
    "images": [
      {
        "id": "y01",
        "filename": "yiyecekler-01.png",
        "path": "/stock-coloring/yiyecekler/yiyecekler-01.png",
        "category": "yiyecekler",
        "title": "Pasta"
      },
      {
        "id": "y02",
        "filename": "yiyecekler-02.png",
        "path": "/stock-coloring/yiyecekler/yiyecekler-02.png",
        "category": "yiyecekler",
        "title": "Dondurma"
      },
      {
        "id": "y03",
        "filename": "yiyecekler-03.png",
        "path": "/stock-coloring/yiyecekler/yiyecekler-03.png",
        "category": "yiyecekler",
        "title": "Pizza"
      },
      {
        "id": "y04",
        "filename": "yiyecekler-04.png",
        "path": "/stock-coloring/yiyecekler/yiyecekler-04.png",
        "category": "yiyecekler",
        "title": "Meyveler"
      },
      {
        "id": "y05",
        "filename": "yiyecekler-05.png",
        "path": "/stock-coloring/yiyecekler/yiyecekler-05.png",
        "category": "yiyecekler",
        "title": "Cupcake"
      },
      {
        "id": "y06",
        "filename": "yiyecekler-06.png",
        "path": "/stock-coloring/yiyecekler/yiyecekler-06.png",
        "category": "yiyecekler",
        "title": "Kurabiye"
      },
      {
        "id": "y07",
        "filename": "yiyecekler-07.png",
        "path": "/stock-coloring/yiyecekler/yiyecekler-07.png",
        "category": "yiyecekler",
        "title": "Donut"
      },
      {
        "id": "y08",
        "filename": "yiyecekler-08.png",
        "path": "/stock-coloring/yiyecekler/yiyecekler-08.png",
        "category": "yiyecekler",
        "title": "Şeker"
      },
      {
        "id": "y09",
        "filename": "yiyecekler-09.png",
        "path": "/stock-coloring/yiyecekler/yiyecekler-09.png",
        "category": "yiyecekler",
        "title": "Hamburger"
      },
      {
        "id": "y10",
        "filename": "yiyecekler-10.png",
        "path": "/stock-coloring/yiyecekler/yiyecekler-10.png",
        "category": "yiyecekler",
        "title": "Karpuz"
      }
    ]
  },
  {
    "id": "sehir",
    "name": "Ev & Şehir",
    "emoji": "🏠",
    "images": [
      {
        "id": "s01",
        "filename": "sehir-01.png",
        "path": "/stock-coloring/sehir/sehir-01.png",
        "category": "sehir",
        "title": "Ev"
      },
      {
        "id": "s02",
        "filename": "sehir-02.png",
        "path": "/stock-coloring/sehir/sehir-02.png",
        "category": "sehir",
        "title": "Binalar"
      },
      {
        "id": "s03",
        "filename": "sehir-03.png",
        "path": "/stock-coloring/sehir/sehir-03.png",
        "category": "sehir",
        "title": "Okul"
      },
      {
        "id": "s04",
        "filename": "sehir-04.png",
        "path": "/stock-coloring/sehir/sehir-04.png",
        "category": "sehir",
        "title": "Oyun Parkı"
      },
      {
        "id": "s05",
        "filename": "sehir-05.png",
        "path": "/stock-coloring/sehir/sehir-05.png",
        "category": "sehir",
        "title": "Park"
      },
      {
        "id": "s06",
        "filename": "sehir-06.png",
        "path": "/stock-coloring/sehir/sehir-06.png",
        "category": "sehir",
        "title": "Köprü"
      },
      {
        "id": "s07",
        "filename": "sehir-07.png",
        "path": "/stock-coloring/sehir/sehir-07.png",
        "category": "sehir",
        "title": "Deniz Feneri"
      },
      {
        "id": "s08",
        "filename": "sehir-08.png",
        "path": "/stock-coloring/sehir/sehir-08.png",
        "category": "sehir",
        "title": "Yel Değirmeni"
      },
      {
        "id": "s09",
        "filename": "sehir-09.png",
        "path": "/stock-coloring/sehir/sehir-09.png",
        "category": "sehir",
        "title": "Çiftlik"
      },
      {
        "id": "s10",
        "filename": "sehir-10.png",
        "path": "/stock-coloring/sehir/sehir-10.png",
        "category": "sehir",
        "title": "Tren İstasyonu"
      }
    ]
  },
  {
    "id": "tatil",
    "name": "Tatil & Özel Günler",
    "emoji": "🎄",
    "images": [
      {
        "id": "t01",
        "filename": "tatil-01.png",
        "path": "/stock-coloring/tatil/tatil-01.png",
        "category": "tatil",
        "title": "Noel Ağacı"
      },
      {
        "id": "t02",
        "filename": "tatil-02.png",
        "path": "/stock-coloring/tatil/tatil-02.png",
        "category": "tatil",
        "title": "Cadılar Bayramı"
      },
      {
        "id": "t03",
        "filename": "tatil-03.png",
        "path": "/stock-coloring/tatil/tatil-03.png",
        "category": "tatil",
        "title": "Paskalya"
      },
      {
        "id": "t04",
        "filename": "tatil-04.png",
        "path": "/stock-coloring/tatil/tatil-04.png",
        "category": "tatil",
        "title": "Doğum Günü"
      },
      {
        "id": "t05",
        "filename": "tatil-05.png",
        "path": "/stock-coloring/tatil/tatil-05.png",
        "category": "tatil",
        "title": "Kardan Adam"
      },
      {
        "id": "t06",
        "filename": "tatil-06.png",
        "path": "/stock-coloring/tatil/tatil-06.png",
        "category": "tatil",
        "title": "Noel Baba"
      },
      {
        "id": "t07",
        "filename": "tatil-07.png",
        "path": "/stock-coloring/tatil/tatil-07.png",
        "category": "tatil",
        "title": "Balkabağı"
      },
      {
        "id": "t08",
        "filename": "tatil-08.png",
        "path": "/stock-coloring/tatil/tatil-08.png",
        "category": "tatil",
        "title": "Sevgililer Günü"
      },
      {
        "id": "t09",
        "filename": "tatil-09.png",
        "path": "/stock-coloring/tatil/tatil-09.png",
        "category": "tatil",
        "title": "Havai Fişek"
      },
      {
        "id": "t10",
        "filename": "tatil-10.png",
        "path": "/stock-coloring/tatil/tatil-10.png",
        "category": "tatil",
        "title": "Hediye Kutusu"
      }
    ]
  }
];

export function getStockCategory(id: string): StockCategory | undefined {
  return STOCK_CATEGORIES.find((c) => c.id === id);
}

export function getAllStockImages(): StockImage[] {
  return STOCK_CATEGORIES.flatMap((c) => c.images);
}
